### ISSUE TITLE
Improve Editable Rectangle

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#10]
Right now dragging corners is allowed everywhere within the image bounds.
This should be improved by not allowing to drag corners on top of each other, as well as not allowing creating shapes that are not quadrilaterals.
This should be implemented in `validPoint()` of `QuadrilateralView`.

**Comment by jcampbell05** [comment]
Could also implement some sort of light snapping (See the way the new measure app in iOS does this for AR measuring) to assist the user.

**Comment by justJS** [comment]
I feel that would be better suited as a new issue or #61/#71
