### ISSUE TITLE
Image size reduction after scanning

### ISSUE THREAD

**Issue by adityashri16** [WeTransfer/WeScan#100]
When image is captured and then flattened , the difference between the original and scanned image is almost double i.e. output image is low quality/size.

Can you please fix or let us know the solution to this? We need more quality images with lesser loss.

Thanks,
Aditya

**Comment by justJS** [comment]
Hey, is there any way to test this easily? Perhaps you can make an example project that displays file sizes of captured images so we can debug this.

**Comment by justJS** [comment]
Hey, I'm not actually a part of the organization that owns this repo - however, you should probablyly keep this open just in case so we/they can make sure it's not actually an issue. 

It might be that there is actually some sort of issue here because #101 has the same problem.

**Comment by adityashri16** [comment]
Hi,

Sorry, I didn't know.
Thanks for letting me know.

keeping it open.

Thanks,
Aditya

**Comment by jcampbell05** [comment]
I'll see if there is some sort of test we can run for this.

**Comment by adityashri16** [comment]
Hey,

I just signed the petition "Narendra Modi , prime minister : Saving future
of 16000 jet airways employees" and wanted to see if you could help by
adding your name.

Our goal is to reach 300,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/GnTPr9zZ5G

Thanks!
aditya
