### ISSUE TITLE
Scanned image quality is reduced by half, even if target doc uses 90 percent of screen.

### ISSUE THREAD

**Issue by n3soni** [WeTransfer/WeScan#101]
Hi @Boris-Em , Today I noticed, scanned images are captured in very low quality as compared to original image. Even if target document uses 90% of the screen. 

On iPhone 6S, original image is of 2.2 mb, whereas scanned one had 880 kb. I had this observation with document occupying 90% of whole screen.

**Comment by justJS** [comment]
This is a duplicate of #100. Could you close this and comment in #100 so we can work on this in one place?

**Comment by n3soni** [comment]
Hi there, I appreciate WeScan team's work. you have made a good product. 
Steps to replicate issue:
I just ran example application and saved this image to PhotoAlbum with this code:
`func imageScannerController(_ scanner: ImageScannerController, didFinishScanningWithResults results: ImageScannerResults) {
        // The user successfully scanned an image, which is available in the ImageScannerResults
        // You are responsible for dismissing the ImageScannerController
        UIImageWriteToSavedPhotosAlbum(results.scannedImage, nil, nil, nil)
        scanner.dismiss(animated: true)
    }`

and then I compared its size with the one captured from camera app. you can test it yourself.
Still, you guys done a fantastic job and it might be the issue with process. but you can explain it better. 

I will close this thread (unresolved), but I would like you see your explanation/fix in #100 .
