### ISSUE TITLE
Create a discussion area for the WeScan Developers, Contributors and Community :)

### ISSUE THREAD

**Issue by jcampbell05** [WeTransfer/WeScan#105]
I was thinking we could us Gitter or something to discuss development of WeScan and other things.

**Comment by justJS** [comment]
Duplicate of #91 🙂 

(It's probably off topic for this issue and I'm not sure on WeTransfer's stance, but seeing as this project has grown to 900+ stars and is getting very popular, it would be nice to have a Slack or discussion chat!)

**Comment by justJS** [comment]
Duplicate of #91 🙂 

(It's probably off topic for this issue and I'm not sure on WeTransfer's stance (cc @Boris-Em @AvdLee), but seeing as this project has grown to 900+ stars and is getting very popular, it would be nice to have a Slack or discussion chat!)

**Comment by jcampbell05** [comment]
> Duplicate of #91 🙂

Should have checked the github :) I'll rename this issue to reference the second thing I brought up as thats not duplicate ;)

**Comment by AvdLee** [comment]
I would love to know how much need for this there is. If anyone is reading this out of interest and wants to have this, lets vote by posting a 👍 on this comment.

**Comment by justJS** [comment]
In case it helps, I feel that a discussion Slack would work not only for perhaps providing a bit of support with installation but also to track releases, discuss PRs/Issues, etc.

**Comment by jcampbell05** [comment]
My only reservation about slack is it can be pretty heavy to setup compared to gitter.im which is integrated into github :)

**Comment by Boris-Em** [comment]
I'd be in favor of Gitter as well. It's lower maintenance as far as I know.

**Comment by justJS** [comment]
Fair enough, I guess I’m favorable towards Slack because I already use it for other things, but a gitter would probably work fine.

**Comment by justJS** [comment]
Has there been any progress on this?
