### ISSUE TITLE
Reorganization of navigation code

### ISSUE THREAD

**Issue by echamussy** [WeTransfer/WeScan#107]
Hi. I'm thinking to add WeScan to a new project I'm working on but the structure of the navigation code seems like it could be improved especially towards supporting multi page scanning. My suggestion in particular is to make the 'ScannerViewController', 'EditScanViewController' independent from a navigation controller navigation. In the ScannerViewController instead of pushing to the EditScanViewController we could create a protocol with a method like 

func scannerViewController(_ scannerViewController:ScannerViewController didCapturePicture picture: UIImage, withQuad quad: Quadrilateral?)

This protocol could be then implemented by the ImageScannerController to push the EditScanViewController but it would also allow to implement your own navigation if the ScannerViewController was to be invoked individually rather than via the ImageScannerController nav controller.

This would also allow to keep the user in the ScannerViewController to support multi page scanning and then show all images scanned in a different controller (similar to what the Scanner PRO from Readdle app does)

Let me know your thoughts. I can try implementing this changes and submit a pull request but I want to know your thoughts first.

Thanks for your great work on this library!

**Comment by justJS** [comment]
Hey, this is already being worked on in issue #11 - if that’s what you wanted it would be best to close this issue so all the discussion is kept in one place 🙂

**Comment by echamussy** [comment]
Thanks for your comment. Ok, I will close this and I will write my comment on issue #11 to keep the discussion in one place. Cheers.

**Comment by justJS** [comment]
Awesome, thanks!
