### ISSUE TITLE
Shouldn't completion be called here?

### ISSUE THREAD

**Issue by valeriyvan** [WeTransfer/WeScan#112]
https://github.com/WeTransfer/WeScan/blob/3ef8b8e49687fead61be62914d53fee61be3b1d8/WeScan/Common/VisionRectangleDetector.swift#L39

**Comment by jcampbell05** [comment]
Yes it should can you submit a PR :) with it calling it with `nil`

**Comment by justJS** [comment]
This is fixed in #130!

**Comment by justJS** [comment]
This is fixed in #115 and can be closed 👍
