### ISSUE TITLE
v1 paper recognition fail, and default language.

### ISSUE THREAD

**Issue by Sjahriyar** [WeTransfer/WeScan#114]
As i updated the library, scanning is not accurate and it doesn’t recognize the paper very well, also default language is set to Chinese!

**Comment by justJS** [comment]
Hi @Sjahriyar, localization seems to be working fine for me. Can you check that your device and target language are set to English, and make sure you're on the latest version of WeScan?

**Comment by Sjahriyar** [comment]
Well for the language it was fixed to english! but somehow it's fixed now! but scanner still doesn't recognise the papers easily, most of the time the white rectangle doesn't appear!

**Comment by jcampbell05** [comment]
@Sjahriyar  can you let us know what version of the library you are using, also if you have a screen capture of the issue that will help alot :)

**Comment by Sjahriyar** [comment]
I’m using the latest version which is 1.0
This is one sample:
https://i.imgur.com/XMlHYic.jpg

No paper detected!
Although if i downgrade to version 0.9.3 it does recognize the papers!

**Comment by justJS** [comment]
@Shahriyar does it work in the sample app?
