### ISSUE TITLE
overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug 

### ISSUE THREAD

**Issue by adityativ-issart** [WeTransfer/WeScan#116]
Sometimes app crashes when trying to detect corners.

**Comment by adityativ-issart** [comment]
it happens at this place:
```
/// Resets the matching score of all of the rectangles in the queue to 0
    private func resetMatchingScores() {
        guard !rectangles.isEmpty else { return }
        for rectangle in rectangles {
            rectangle.matchingScore = 1
        }
    }
```
in the RectangleFeaturesFunnel class.

**Comment by adityativ-issart** [comment]
@Boris-Em Yes, it is pretty random. I have also a question about detect corners for a image from photo library. Can that framework detect borders for the photo from photo library?

**Comment by justJS** [comment]
@adityativ-issart It doesn't actually show the picker: the host app must pass a image picked by the user to WeScan in the new `init`.

**Comment by adityativ-issart** [comment]
@Boris-Em could you take an example, please?

**Comment by Boris-Em** [comment]
The sample project is here for that @adityativ-issart.

**Comment by Cyberbeni** [comment]
Accessing the rectangles array happens on the same queue as detecting the rectangle with vision framework which is a DispatchQueue.global(qos: .userInitiated) which always grabs a random queue instead of being a serial queue, that's why it sometimes crashes. (you want to start the detection of the next rectangle before the previous one finishes but the result handling should be done on serial queue)

**Comment by marinofaggiana** [comment]
any news here ?

**Comment by erikvillegas** [comment]
I also ran into this crash that happens randomly: https://imgur.com/a/7sg6O8U

**Comment by marinofaggiana** [comment]
This version 1.0 is pretty dangerous and unstable ... @justJS

**Comment by justJS** [comment]
Hey @marinofaggiana - I am not the owner of the project. However, I will look at the issue and see if I can create a PR to resolve it.

**Comment by marinofaggiana** [comment]
@justJS thanks a lot for your job, now we use the old version 0.9.1, the autodetect generates the mistake.

**Comment by xiaotaner** [comment]
I have same issue, crash in func resetMatchingScores

**Comment by xiaotaner** [comment]
> Accessing the rectangles array happens on the same queue as detecting the rectangle with vision framework which is a DispatchQueue.global(qos: .userInitiated) which always grabs a random queue instead of being a serial queue, that's why it sometimes crashes. (you want to start the detection of the next rectangle before the previous one finishes but the result handling should be done on serial queue)

Do you have any idea to solve it ? @Cyberbeni , thanks

**Comment by xiaotaner** [comment]
I delete the code about **DispatchQueue.global** in VisionRectangleDetector.swift file, it works correctly; 
I think it is because all works after **captureOutput:didOutputSampleBuffer:fromConnection:** is in a same queue, so it do not need create a new queue;
As Apple say:
/*
@method captureOutput:didOutputSampleBuffer:fromConnection:

 @discussion
    Delegates receive this message whenever the output captures and outputs a new video frame, decoding or re-encoding it as specified by its videoSettings property. Delegates can use the provided video frame in conjunction with other APIs for further processing. **This method will be called on the dispatch queue specified by the output's sampleBufferCallbackQueue property**. This method is called periodically, so it must be efficient to prevent capture performance problems, including dropped frames.
*/

**Comment by erikvillegas** [comment]
@xiaotaner Do you mind submitting a pull request with the fix, or at least provide a small snippet of code with the changes? Very eager to get this fixed in my app as well. :)
