### ISSUE TITLE
Improve Quad Detection and Enhancement based on Dropbox Document Scanner

### ISSUE THREAD

**Issue by winstonschen** [WeTransfer/WeScan#119]
The Dropbox apps comes with excellent document scanning capabilities. Its page detection and post processing are very good. It would great if WeScan can develop capabilities that approximates that of the Dropbox app. Dropbox did reveal some of the core ideas in their blog:

[https://blogs.dropbox.com/tech/2016/08/fast-and-accurate-document-detection-for-scanning/](url)

and

[https://blogs.dropbox.com/tech/2016/08/fast-document-rectification-and-enhancement/](url)

**Comment by Boris-Em** [comment]
Thanks for opening this @winstonschen! 
Your ticket is a bit too generic.
It would be more useful to us if you could list specific cases where our implementation falls short of Dropbox's.
