### ISSUE TITLE
Improve Image Enhancement Based on Dropbox Document Scanner

### ISSUE THREAD

**Issue by winstonschen** [WeTransfer/WeScan#120]
Currently the only enhancement is` applyingAdaptiveThreshold()` which works well only under ideal lighting conditions and only produces BW images.

Dropbox Document Scanner contains a very good enhancement algorithm described here:

[Fast Document Rectification and Enhancement](https://blogs.dropbox.com/tech/2016/08/fast-document-rectification-and-enhancement/)

The algorithm accounts for uneven lighting across the page to create crisp text. It also restores the exact color of the original text and images. 

The blog post doesn't contain a lot details, but it would be great for an image processing expert among us to take those ideas and implement them.

**Comment by justJS** [comment]
Hey @winstonchen, I actually implemented the current enhancement filter with CoreImage in a pull request a few months ago. 

I’m aware of Dropbox’s algorithm, but I do feel like it would be very hard to match: and I’m not sure on WeTransfer’s stance on the possible legal issues.

Do you have any ideas on how to implement this?

**Comment by weinixuehao** [comment]
@winstonschen 
Have you implemented The drop box algorithm now?

**Comment by jcampbell05** [comment]
So it seems the dropbox also uses some special handling for how close a pixel is to white

**Comment by winstonschen** [comment]
At WWDC, an Apple developer showed me this gem:

`inputCIImage.applyingFilter("CIDocumentEnhancer")`

It's very good and works in iOS 11 and above.

**Comment by jcampbell05** [comment]
Such a shame it's not a documented filter but great we have something
