### ISSUE TITLE
Improve Quad Detection

### ISSUE THREAD

**Issue by winstonschen** [WeTransfer/WeScan#121]
The Dropbox apps comes with excellent document scanning capabilities. Its page/quad detection is very good -- better than `CIDetector` or `VNDetectRectanglesRequest`. It would great if WeScan can develop capabilities that approximates this. Dropbox did reveal some of the core ideas in their blog:

[Fast and Accurate Document Detection for Scanning](https://blogs.dropbox.com/tech/2016/08/fast-and-accurate-document-detection-for-scanning/)

The blog post doesn't contain any code. And one part of the pipeline requires human-created training data.

**Comment by jcampbell05** [comment]
@winstonschen if you have anyone who has expertise in this that would be great :) I'm not an AI expert

**Comment by justJS** [comment]
Not sure what other contributors think, but here are my two cents:

I really don’t think a custom quad detection algorithm, even if very good, is a good idea.

While a custom algorithm may be better, it would be hard to maintain, and if whoever contributed it stopped helping out, we’d be stuck with a unmaintainable detection algorithm. Furthermore, it would require constant training, and may add considerable weight to the framework.

On the other hand, Vision (which we now use for iOS 11+) is getting trained by Apple and getting better each year, for example, I believe Apple spoke about how Vision has already improved in iOS 12.

What do others think about this?

**Comment by mikeperrett** [comment]
At the very least it would helpful to allow options to be passed to your main controller to initialize the CIDetector with the CIDetectorAspectRatio.
Currently, it appears that anything less than 0.5 cannot be scanned

**Comment by justJS** [comment]
Hey @mikeperrett, I don't see where we're currently forcing the aspect ratio? Just for additional information, which version of iOS do you happen to use?

**Comment by mikeperrett** [comment]
@justJS I’m using iOS 12 on both devices. 
I’m not familiar with code, but  have a hunch that the default value 0.5 of the vision framework is preventing me from scanning anything of interest (my documents are all rather tall; 2x6 or 2x8) 
https://developer.apple.com/documentation/vision/vndetectrectanglesrequest/2875378-minimumaspectratio

**Comment by justJS** [comment]
iOS 11 and above uses Vision instead of CoreImage. I'm not sure if that's the issue but I'll check later.

**Comment by mikeperrett** [comment]
@justJS 
Thanks for the reply. Unfortunately all 5 of my devices are above 12.x so I cannot confirm the behavior pre-11.x.

As a test, with the WeScanSample app I modified
VisionRectangleDetector::rectangle, line 50 with
`rectDetectRequest.minimumAspectRatio = 0.3`

I am able to scan my 2" x 6" and 3" x 10" documents now.

Couple of questions, 
1. I wasn't sure if I should move this over to issue:
[#137](https://github.com/WeTransfer/WeScan/issues/137)

2. Would it be OK to make a pull request to add a minimumAspectRatio as a property of your main controller and pass it to CIDetector::CIDetectorAspectRatio and VNDetectRectangleRequest::minimumAspectRatio

**Comment by mikeperrett** [comment]
@justJS Quick follow up; fwiw, I have confirmed that (my iOS devices > iOS 11.x) are able to scan the narrow documents using the CIRectangleDetector in CoreImage.

**Comment by mikeperrett** [comment]
I created a pull request that does the bare minimum of adding a default value 0.1 aspect ratio to allow many other documents to succeed rectangle detection in iOS 11.x and later.
https://github.com/WeTransfer/WeScan/pull/139

**Comment by MentalGear** [comment]
Having a customizable value would of course be best :)
