### ISSUE TITLE
Skip review

### ISSUE THREAD

**Issue by piotrros** [WeTransfer/WeScan#122]
Hello, is it possible to completely skip review stage? So, you have a picture, fix the edges and after tapping "Next" you're done with an UIImage, so you skip review stage, which to me is unnecessary. Just an extra question: is it possible to localize this library while still using it from cocoa pods or I'm forced to create a fork?

**Comment by justJS** [comment]
We already have a few localizations and you can create a PR to add more!

I believe the request to skip review is a semi-duplicate of #21, what do you think @Boris-Em @AvdLee?

**Comment by piotrros** [comment]
In the end, I simply copied source files directly to my project and changed everything to fit my needs :)

**Comment by justJS** [comment]
Awesome, happy to hear you fixed the issue 😃

**Comment by igorkaryi** [comment]
@piotrros please, share an example code. how did you get rid of the second screen edit
