### ISSUE TITLE
CameraRoll Support (Bug)

### ISSUE THREAD

**Issue by fatenumber25** [WeTransfer/WeScan#123]
I'm used version
pod 'WeScan', :git => 'https://github.com/WeTransfer/WeScan.git'

then when I start scan image which picked from camera roll, I got wrong detected rectangle.
How can I fix that?

![photo_d10405_0128072031788](https://user-images.githubusercontent.com/22123971/51807725-1ad0a700-22ce-11e9-9a99-8088b75673ec.png)

**Comment by justJS** [comment]
Hey @fatenumber25, as noted by @jcampbell05 could you provide the requested information so we can check if we can reproduce the issue?

**Comment by xiaotaner** [comment]
I have same issue;
When i pick image from Photos Library,i got the wrong detector rectangle;
I use iPhone5s(iOS12.1) and iPhone6(iOS11.4.1) and iPhone7 plus(iOS12.1) all devices got wrong detector rectangle;
Screen capture like this ![Screen capture](https://github.com/xiaotaner/about/blob/master/QQ20190220-200650%402x.png)

**Comment by fatenumber25** [comment]
I'm really sorry for late reply!!  
I'm using iPad (5th generation) device. And the image as below.  
![img_2533](https://user-images.githubusercontent.com/22123971/53275818-e8d12a00-373f-11e9-8ae3-518604d93ca5.JPG)

**Comment by jcampbell05** [comment]
Yeah it looks like we aren't taking into account the orientation header. The image data is portrait hence why the rectangle is where it is but we then fail to rotate it 90 degrees based on the metadata. A very annoying iOS thing.

We just need to read this value here @justJS  :)
<img width="532" alt="screen shot 2019-02-24 at 21 25 59" src="https://user-images.githubusercontent.com/1484989/53305557-ce4f9b80-387a-11e9-9d48-0572bdd1ae70.png">

**Comment by holtwick** [comment]
Or just normalize it before processing: 

```objc
    UIImage *normalizedImage = image;
    if (image.imageOrientation != UIImageOrientationUp) {
        UIGraphicsBeginImageContextWithOptions(image.size, NO, image.scale);
        [image drawInRect:(CGRect){0, 0, image.size}];
        normalizedImage = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
    }
```

https://stackoverflow.com/a/10611036/140927

**Comment by AlbertArredondoAlfaro** [comment]
Same issue here. Any idea on how to fix it?

**Comment by jcampbell05** [comment]
@AlbertArredondoAlfaro we just need someone to submit a PR with the above fixes :)

**Comment by yangchen-acc** [comment]
Hi guys, I issued a PR to fix this issue, could you take some time to review it? Thanks!
https://github.com/WeTransfer/WeScan/pull/165

**Comment by yangchen-acc** [comment]
#165

**Comment by EricWiener** [comment]
For others running into this issue, update Podfile to get fixes:
`pod 'WeScan', :git => 'https://github.com/WeTransfer/WeScan.git', :commit => '2beccd392966b19d8215a4e0054d7c9320520094'`

**Comment by mstralka** [comment]
Looking at the previous comment and PR #165, I think this issue is fixed and can be closed?
