### ISSUE TITLE
Move View(/layout) code out of Controller classes

### ISSUE THREAD

**Issue by Cyberbeni** [WeTransfer/WeScan#124]
Setting up the views should be done in a UIView subclass and then referenced in the VC's loadView like this:

```
override func loadView() {
    self.view = MyView()
}
```

**Comment by AvdLee** [comment]
@Cyberbeni it's not our plan to implement code like that, we're used to working with subviews. Thanks for your feedback though and feel free to help us improve our code by opening a pull request.
