### ISSUE TITLE
Allow for the customisation of the font and navigation colors

### ISSUE THREAD

**Issue by teatreejasmine** [WeTransfer/WeScan#128]

**Comment by justJS** [comment]
Hi, while the font can't be customized, it's already possible to edit the navigation colors by changing the `tintColor` and `barStyle` of the `ImageScannerController` before presenting it. Is this what you were looking for?

**Comment by justJS** [comment]
Hey @teatreejasmine, you can also customize the font of the entire app, which should change WeScan as well, like this:

```UILabel.appearance().font = UIFont(name: "yourFont", size: yourSize)```

Is there anything else you were looking to customize?

**Comment by AvdLee** [comment]
Closing this one for now. @teatreejasmine feel free to reopen if you have any more questions.
