### ISSUE TITLE
Unable to access result rectangle coordinate points

### ISSUE THREAD

**Issue by benwagucla** [WeTransfer/WeScan#131]
I am trying to access the the final rectangle's quad points, however I receive an error saying all the aspects of the rectangle (ex: "top left") are inaccessible due to internal protection level. Is there any way of accessing the rectangles coordinates?

**Comment by justJS** [comment]
Thanks for the report @benwagucla! This is a mistake, I've created a PR which fixes it: #132

**Comment by benwagucla** [comment]
Really appreciate the quick response!

**Comment by justJS** [comment]
@benwagucla This has now been fixed on the `develop` branch! It should be merged into master/CocoaPods eventually
