### ISSUE TITLE
Cordova support ?

### ISSUE THREAD

**Issue by crapthings** [WeTransfer/WeScan#136]
how easy to integrate wescan into cordova ?

**Comment by AvdLee** [comment]
@crapthings we don't have experience with Cordova. WeScan can be added as a native dependency which should work just like with other frameworks. Please, take a look at implementing frameworks in Cordova and see if that works!

**Comment by ChrisTomAlx** [comment]
@crapthings and anyone else looking for a cordova plugin
Ver 3.x.x of this [plugin](https://www.npmjs.com/package/cordova-plugin-document-scanner) supports the latest cocoapod of this library. 

You can add it to your project as below using npm and cordova cli
`cordova plugin add cordova-plugin-document-scanner@3.x.x`

**Plugin Usage Example**
```
scan.scanDoc(onSuccess, onFail, {sourceType:1}); // sourceType will by default take value 1 if no value is set | 0 for gallery | 1 for camera

function onSuccess(imageURI) {
    alert(imageURI);
    console.log(imageURI);
    //var image = document.getElementById('myImage');
    //image.src = imageURI; // For iOS, use image.src = imageURI + '?' + Date.now(); to solve issue 10

}

function onFail(message) {
    alert('Failed because: ' + message);
}
```

**Important tasks after build - DO NOT skip**
> 1. Open xcworkspace file using xcode within the platforms/ios folder.
> 2. Select the project, this opens up project settings. Now within General, set deployment target in xcode as 10 or above
> 3. In build settings set swift language version to 4.0
> 4. In build settings set Objective C bridging header to HelloCordova/Plugins/cordova-plugin-document-scanner/ScanPlugin/Bridging-Header.h where HelloCordova is your project name

Thanks a lot to everyone who has worked on this library. I cannot begin to express how amazing the usage (from an user experience perspective) is. Keep up the good work. I will try and keep up with the latest cocoapod releases.

> PS : This version of the plugin is still in its infancy and it uses swift 4.0, cordova uses objective C as its core language, so there could be possible clashes with other plugins. Please do use with care if you are using it in a project with a lot of plugins.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
