### ISSUE TITLE
Allow Passing the Aspect Ratio Threshold

### ISSUE THREAD

**Issue by mikeperrett** [WeTransfer/WeScan#137]
@Boris-Em @justJS 
It works great for most documents. Unfortunately, I cannot use the scanner since the documents I'm expecting are not within what appears to be the default aspect ratio of 0.5. (Documents I’m scanning are 2x6 or taller).

**Can we pass in the CIDetectorAspectRatio, and other options?**
https://developer.apple.com/documentation/coreimage/cirectanglefeature
https://developer.apple.com/documentation/coreimage/cidetectoraspectratio

If we allowed options to be passed in, we could create another convenience initializer for the CIDetector, perhaps something like:

`
convenience init?(aspectRatio: Float = 1.0) {  
  let options: [String : Any] = [CIDetectorAccuracy : CIDetectorAccuracyHigh,
                                       CIDetectorAspectRatio : NSNumber(value: aspectRatio)
`
Or
`
convenience init?(options: Any)
`

 Is this something that has been considered already?

**Comment by justJS** [comment]
This is fixed in #139

**Comment by justJS** [comment]
This issue is fixed and can be closed as per #139
