### ISSUE TITLE
Toolbar Enhance Button and Rotation on Edit Screen(Bug)

### ISSUE THREAD

**Issue by PrincessMine** [WeTransfer/WeScan#144]
I have used the version
pod 'WeScan', '>= 0.9'

This is first time I am posting an issue so please ignore if it seems derogatory comment.

1). When I capture an image and come to edit screen bottom enhance button is not working for the first time click.
2). While clicking 2 times that button it works than rotate the image, the image gets change to original image.
3). Once I rotate first and do apply the enhancement it is working for every-time rotation after that.

To get clear idea I am attaching the video file of this issue.

Thanks,
Aashi Shaikh.

[Wescan_issue.mov.zip](https://github.com/WeTransfer/WeScan/files/2965142/Wescan_issue.mov.zip)

**Comment by Boris-Em** [comment]
Thanks for reporting this bug @PrincessMine! 
You can track the progress of the fix on this PR #145.
