### ISSUE TITLE
how to add wescan.framework? where to find it?

### ISSUE THREAD

**Issue by crapthings** [WeTransfer/WeScan#147]
cant find this one

![image](https://user-images.githubusercontent.com/1147704/54972699-cabd4a80-4fc7-11e9-9484-bee254e2df3c.png)

**Comment by crapthings** [comment]
![image](https://user-images.githubusercontent.com/1147704/54980112-db79ba80-4fdf-11e9-8159-9188da12c070.png)

i dont see wescan.framework, but it works.

**Comment by IosXcodeDeveloper** [comment]
Same question here. Where is the framework file ?
