### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by crapthings** [WeTransfer/WeScan#148]
what is wrong?

![image](https://user-images.githubusercontent.com/1147704/54982997-e3892880-4fe6-11e9-9308-2cdef062c1e8.png)

**Comment by Boris-Em** [comment]
Hi @crapthings!
How did you import the framework?

**Comment by crapthings** [comment]
pod install?

**Comment by crapthings** [comment]
i think its my gem and pod problem, i've upgraded those tool, and change xcodeproj format to

![image](https://user-images.githubusercontent.com/1147704/55051334-9c0aa700-508f-11e9-8451-eaed1ced743c.png)

then pod install
