### ISSUE TITLE
Image from gallery rotation issues.

### ISSUE THREAD

**Issue by vikricnik** [WeTransfer/WeScan#150]
there seem to be an issue with rotation of detected image, it seems upside down when i select it from camera roll.

![IMG_4589](https://user-images.githubusercontent.com/49037898/55422505-12217900-557c-11e9-846b-075800a20bcb.JPG)
![IMG_4590](https://user-images.githubusercontent.com/49037898/55422522-19e11d80-557c-11e9-8761-187d338bcaaa.JPG)

**Comment by jcampbell05** [comment]
There is already an issue related to this can you close this 😀

**Comment by vikricnik** [comment]
closed in favour of [issue](https://github.com/WeTransfer/WeScan/issues/123#issue-403602990)
