### ISSUE TITLE
Different ImageScannerController initialization between carthage's framework and sample project

### ISSUE THREAD

**Issue by ogulcankeskin93** [WeTransfer/WeScan#151]
I tried to use scanner on selected image. But I use carthage to fetch and there is no initialization with image 'ImageScannerController(image: image, delegate: self)' inside framework.

**Comment by naoya0731** [comment]
try 1.1.0

on 1.0.0, 'ImageScannerController(image: image, delegate: self)' is missing. I don't know why...

**Comment by AvdLee** [comment]
Probably related to our code updates :)
