### ISSUE TITLE
Swift Compiler error

### ISSUE THREAD

**Issue by MikeFr** [WeTransfer/WeScan#155]
Hi,

I used Cocoapods to include the version 1.1.0 in my project (swift 4 here) but there are several compiler errors : 

![image](https://user-images.githubusercontent.com/282292/55866429-a002f280-5b80-11e9-8434-3cbd5da48a03.png)

I tried with the versions 0.9.1, same issues. Any ideas ?

Thanks, 
Mike

**Comment by AvdLee** [comment]
The library now uses Swift 5.0 which should fix your issues!
