### ISSUE TITLE
Missing Cancel button

### ISSUE THREAD

**Issue by ManvelHovhannisyan** [WeTransfer/WeScan#162]
Pick a photo from photo library to scan and check cancel button is missing.

**Comment by sandeepsuthar** [comment]
I have same issue

**Comment by EricWiener** [comment]
Try using #165. This issue was resolved in it. If you're using CocoaPods:

`pod 'WeScan', :git => 'https://github.com/WeTransfer/WeScan.git', :commit => '2beccd392966b19d8215a4e0054d7c9320520094'`
