### ISSUE TITLE
Crash on IPAD landscape

### ISSUE THREAD

**Issue by jbarros35** [WeTransfer/WeScan#163]
WeScan is crashing on iPad locked on landscape

 *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [WeScan.ImageScannerController shouldAutorotate] is returning YES'
*** First throw call stack:
(0x1d4f7b518 0x1d41569f8 0x1d4e85c70 0x200b76a40 0x200b6703c 0x200b763b4 0x200a91df4 0x200a88490 0x200b6a908 0x200b6c3a0 0x200b6ea7c 0x200b6ef78 0x200b6e9d4 0x200b6ec34 0x1048b2318 0x1048b25f8 0x200b5a8f8 0x200acad38 0x200acb040 0x200acbf7c 0x200acd210 0x200ab0420 0x20158be54 0x1d94091f0 0x1d940e198 0x1d93710a8 0x1d939f108 0x1d939fcf8 0x1d4f0c89c 0x1d4f075c4 0x1d4f07b40 0x1d4f07354 0x1d710779c 0x201103b68 0x1049c0db4 0x1d49cd8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

Can you please provide me a solution? It works on iPhone because its on portrait mode.

**Comment by premsai456** [comment]
Hi jbarros35 ... have you get any solution for this issue... i am also facing the same issue,....  if you found any solution please help us

**Comment by AvdLee** [comment]
We didn't fully test WeScan yet on iPad. It should be fairly easy to fix! @Boris-Em we'll probably run into this with our current work

**Comment by mrlazy1324** [comment]
> WeScan is crashing on iPad locked on landscape
> 
> *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [WeScan.ImageScannerController shouldAutorotate] is returning YES'
> *** First throw call stack:
> (0x1d4f7b518 0x1d41569f8 0x1d4e85c70 0x200b76a40 0x200b6703c 0x200b763b4 0x200a91df4 0x200a88490 0x200b6a908 0x200b6c3a0 0x200b6ea7c 0x200b6ef78 0x200b6e9d4 0x200b6ec34 0x1048b2318 0x1048b25f8 0x200b5a8f8 0x200acad38 0x200acb040 0x200acbf7c 0x200acd210 0x200ab0420 0x20158be54 0x1d94091f0 0x1d940e198 0x1d93710a8 0x1d939f108 0x1d939fcf8 0x1d4f0c89c 0x1d4f075c4 0x1d4f07b40 0x1d4f07354 0x1d710779c 0x201103b68 0x1049c0db4 0x1d49cd8e0)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> 
> Can you please provide me a solution? It works on iPhone because its on portrait mode.

Hi @jbarros35 ,  Have you get any solution for this issue? Any update I still facing this issue

My iPad app only supports landscape mode and camera of this library is show me always wron view

**Comment by mrlazy1324** [comment]
In this crash is solved by changing in 

filename: ImageScannerController.swift
line number: 60
override public var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .landscape //.portrait
    }


But Camera view not setting up to the landscape, I tried to change this in CaptureSessionManager.swift file
 
videoPreviewLayer.connection?.videoOrientation = .landscapeLeft

but not changed please help in change camera video position
iPad screenshot
[https://drive.google.com/file/d/1DWzOEp4oa9l8KjPEwJSI4kzl5nbF2KEz/view?usp=sharing](url)

**Comment by AvdLee** [comment]
@mrlazy1324 Sorry that this is still happening! We're open to receive any PRs to fix this issue 🙂

**Comment by willm132** [comment]
Has anyone been able to fix this yet? My app only works in landscape and the camera pops up in orientation.
