### ISSUE TITLE
Unable to call weScan from Objective-c with modified  code.

### ISSUE THREAD

**Issue by takhil** [WeTransfer/WeScan#167]
From Objective -c I am calling we scan like this.

**ImageScannerController *imageScanner = [[ImageScannerController alloc] init ];
[self presentViewController:imageScanner animated:true completion:nil];**

But with updated code this is not working. Because there is no "init" method in ImageScannerController. We must need to pass image or nil to that constructor method. But that method while allocating the class(typing suggestions).

**Comment by AvdLee** [comment]
This should be easy to fix in a PR. Feel free to open one and I'm happy to take a review!

**Comment by arashetm** [comment]
If you want to init an instance without parameters you can edit `init` method in `ImageScannerController` like this :

```
public required init() {
        super.init(rootViewController: ScannerViewController())
        
        navigationBar.tintColor = .black
        navigationBar.isTranslucent = false
        self.view.addSubview(blackFlashView)
        setupConstraints()
    }
```
