### ISSUE TITLE
Could not find module 'WeScan' for architecture 'armv7'; found: arm64

### ISSUE THREAD

**Issue by Kritesh7** [WeTransfer/WeScan#169]
import WeScan
I am facing problem Could not find module 'WeScan' for architecture 'armv7'; found: arm64
in Swift 4 please help me Thanks

**Comment by AvdLee** [comment]
@Kritesh7 let us know if this still stops you from using WeScan. We did not receive any more issues like this, so it would be great to have reproduction path.
