### ISSUE TITLE
Add iOS 13 notes.

### ISSUE THREAD

**Issue by jcampbell05** [WeTransfer/WeScan#170]
iOS 13 finally adds a view controller in the SDK which does the same thing as WeScan, 
it may be a good idea to add a note to recommend people use that instead of WeScan for iOS 13 and above.

Eventually once iOS 10 - 12 isn't needed resources can then instead be deployed to the android port until Android gains it's own version.

**Comment by AvdLee** [comment]
Good idea! Question is whether it completely replaces WeScan. It looks good, but is not close to WeScan yet. It feels a bit buggy still, but if so, we should definitely add that to our readme!
