### ISSUE TITLE
Update API to match iOS 13

### ISSUE THREAD

**Issue by jcampbell05** [WeTransfer/WeScan#171]
For better compatibility it may be a good idea to try and create an API closer to the new View Controller API in iOS 13 https://developer.apple.com/documentation/visionkit/vndocumentcamerascan

**Comment by AvdLee** [comment]
@justJS you played around with this new API. What are your thoughts on this?

**Comment by justJS** [comment]
The official API is very similar to WeScan’s already! I’m currently traveling but I’ll check this out when I get back to Hong Kong 🙂
