### ISSUE TITLE
Crash while capturing the image in iOS 12

### ISSUE THREAD

**Issue by sajangandhi2019** [WeTransfer/WeScan#174]
We have used the latest version WeScan library in our app and it crashes while capturing the image in  **RectangleFeaturesFunnel** class in below mentioned method:

private func resetMatchingScores() {
        guard !rectangles.isEmpty else { return }
        for rectangle in rectangles {
            rectangle.matchingScore = 1
        }
    }

**Comment by AvdLee** [comment]
@sajangandhi2019 thanks for reporting in. Do you have any crashlogs and reproduction paths?

**Comment by ChandniPambhar123** [comment]
@AvdLee  I am also facing same issue with ios 12. Can you please help me to fix?

**Comment by lokishengoku** [comment]
@AvdLee  I'm facing the same issue (ios 12.5.6). App crash after launch camera 1-2 seconds. Please help?

**Comment by AvdLee** [comment]
@lokishengoku we're no longer supporting iOS 12, unfortunately. The only thing you can do is forking this project, add back support, and see if you can fix the crash
