### ISSUE TITLE
Embedding with Objective-C.

### ISSUE THREAD

**Issue by johnmccambridge7** [WeTransfer/WeScan#175]
I've found an issue with the setup involving objective-c with the swift library. Inside ImageScannerController.swift the init method is not being called when the scanner is called within Objective-C. 

public required init() {
        let scannerViewController = ScannerViewController()
        super.init(rootViewController: scannerViewController)
        navigationBar.tintColor = .black
        navigationBar.isTranslucent = false
        self.view.addSubview(blackFlashView)
        setupConstraints()
    }

Must be added inside to get this to work.

**Comment by AvdLee** [comment]
@johnmccambridge7 feel free to open a PR for this!

**Comment by AvdLee** [comment]
Closing as duplicate of https://github.com/WeTransfer/WeScan/issues/167
