### ISSUE TITLE
Getting the Italian localization, although my iPhone is set to (only) English

### ISSUE THREAD

**Issue by oferRounds** [WeTransfer/WeScan#177]
Seeing this also on other phones

Any idea? I guess this relates to one of the latest PRs, which added Italian localization

**Comment by oferRounds** [comment]
Hi @AvdLee any chance you could have a look on this?

**Comment by jcampbell05** [comment]
It depend on how the localisation folders were configured - potentially it's implemented in a way that it defaults to Italian in certain circumstances i.e if the phone requests UK English but we've only provided US English rather than stating that we are supporting Generic English.

**Comment by AvdLee** [comment]
@oferRounds can you reproduce it with the example project? And which language is your phone set if this occurs?

**Comment by oferRounds** [comment]
My phone is set to English US. I can try, sure
