### ISSUE TITLE
Auto and Flash buttons are not rendered on iOS 13

### ISSUE THREAD

**Issue by evanjd** [WeTransfer/WeScan#181]
The **Auto** and **Flash on/off** buttons are not visible on iOS in `ScannerViewController`. This doesn't appear to be related to light/dark mode settings.

See below - top screen is from iOS 13 GM, bottom is from iOS 12.4.

![Screen Shot 2019-09-18 at 8 21 47 pm](https://user-images.githubusercontent.com/4055224/65140490-03f3e600-da52-11e9-9604-cb391cbd32f6.png)

**Comment by evanjd** [comment]
This looks like an issue with `visualEffectView` [here](https://github.com/WeTransfer/WeScan/blob/develop/WeScan/Scan/ScannerViewController.swift#L101) not being moved behind the navigation bar items.

**Comment by arashetm** [comment]
Change these 2 lines in `ScannerViewController` :
```
navigationController?.navigationBar.addSubview(visualEffectView)
navigationController?.navigationBar.sendSubviewToBack(visualEffectView)
```
To: 
```
visualEffectView.layer.zPosition = -1
visualEffectView.isUserInteractionEnabled = false
navigationController?.navigationBar.insertSubview(visualEffectView, at:0)
```

**Comment by fredmoraes** [comment]
I'm testing on iOS 12.4.4, and the error persists. This time, the NavigationBar background and buttons are turning white. However, auto and flash buttons remain clickable.
