### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 

### ISSUE THREAD

**Issue by alxrguz** [WeTransfer/WeScan#184]
In the Xcode 11 available in the App Store, it is not possible to compile the project. Error text:
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/alxrguz/Library/Developer/Xcode/DerivedData/Scanner-gkkuymtwiaxrucaowypvkmjfrzlx/Build/Products/Debug-iphoneos/WeScan.framework/Modules/WeScan.swiftmodule/arm64.swiftmodule

**Comment by dulgan** [comment]
You just need to do a `carthage update` to solve this issue after XCode 11 installation.
