### ISSUE TITLE
Wrong cropped image

### ISSUE THREAD

**Issue by hadiidbouk** [WeTransfer/WeScan#191]
I was trying to test the application with my iPhone 11 ( also tested in iPhone XS max), but it seems that the image edited are not cropped correctly, I don't know if it's a problem with iOS 13 or even these iPhones has a better camera. here is the image that I tested.
![Image from iOS](https://user-images.githubusercontent.com/19314956/67624318-c85df000-f837-11e9-98fb-f32d5330e43c.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/19314956/67624320-c8f68680-f837-11e9-893d-d8198ddfa050.png)

**Comment by EricWiener** [comment]
I'm also having this issue on an iPhone running iOS 12. It only happens with some images though.

**Comment by hadiidbouk** [comment]
Any idea what is causing the problem?

**Comment by EricWiener** [comment]
I think this is solved by #165 but I'm not able to get this through pod update and manually installing doesn't work because there are a couple of errors in master preventing me from complilingr.

**Comment by hadiidbouk** [comment]
I see, but this guy mention that these changes are not released yet, https://github.com/WeTransfer/WeScan/pull/165#issuecomment-518628408, you cannot access them via pod, you should copy the files or specify the commit

**Comment by EricWiener** [comment]
Updating my podfile to:
`pod 'WeScan', :git => 'https://github.com/WeTransfer/WeScan.git', :commit => '2beccd392966b19d8215a4e0054d7c9320520094'`

Fixed everything and gave me no compile errors.

**Comment by EricWiener** [comment]
I just tested with a couple more photos and I’m still running into the same issue

**Comment by jcampbell05** [comment]
in another issue - its due to orientation.

**Comment by EricWiener** [comment]
I tried installing manually vs. as a pod and specifying a commit. I manually installed the develop branch and now everything is working. This also fixed all the other issues I was having: the cancel button appears and localization works.

**Comment by mariogalvaozup** [comment]
I've got the same problem on version 1.5.0. Any fix?
