### ISSUE TITLE
Language appearing in Chinese

### ISSUE THREAD

**Issue by EricWiener** [WeTransfer/WeScan#196]
I'm on a phone that is set to English (and has never been set to anything but English). This also occurs on simulators. Most of the cropping buttons appear in Chinese (except the Done button is in English). Not sure what I can do to avoid this. It has been like this for a while now. I installed WeScan through cocoapods.

**Comment by EricWiener** [comment]
I ended up temporarily resolving the issue by replacing all localization strings with the English labels. Not a good solution though. Would appreciate some advice.

**Comment by EricWiener** [comment]
Resolved entirely by manually installing WeScan vs. using CocoaPods.

**Comment by EricWiener** [comment]
This is still an issue when installing with CocoaPods

**Comment by oferRounds** [comment]
Seeing this also, on my case – getting Russian. I believe this should be reopened

**Comment by LucaComanducci** [comment]
This problem occurr also to me: device in Italian -> German localization. This issue should be reopened!

**Comment by sclee15** [comment]
Korean locale but not showing message with the default en.lproj This issue should be reopened!
