### ISSUE TITLE
Save as PDF by Default 

### ISSUE THREAD

**Issue by samuelbeek** [WeTransfer/WeScan#20]
## What is the problem
I think we should save the documents as PDF by default, because: 
* All other scan apps do this (Dropbox, Scanbot).
* Hardware Scanners do it.
* People are most likely to "scan" documents. 
  * PDF is the standard for scanned documents - there's no clear data on this, but if you read [this](http://www.soliddocuments.com/pdf/_standards_format/253/11) and take into consideration that all actual scanners using PDF as well, I think there's a good case to be made. 
  * Most documents contain text, JPEG makes text unreadable.

**Comment by jcampbell05** [comment]
I second this, whats best way of doing this ?

**Comment by Boris-Em** [comment]
[PDFKit](https://developer.apple.com/documentation/pdfkit) makes this pretty easy, but it's only supported on iOS 11+.
Maybe we could drop support of iOS 10 for this specific feature @samuelbeek, @jcampbell05?

**Comment by justJS** [comment]
I think this feature should be opt in by the creators of the app who use the framework - for example, my usage for WeScan would not use PDFs.

**Comment by samuelbeek** [comment]
@Boris-Em I agree that we could make it an iOS 11 only feature.

**Comment by Boris-Em** [comment]
Good point @justJS!

**Comment by jcampbell05** [comment]
Some companies will be dropping iOS 10 support soon so I think there is little value trying to port PDF to iOS 10. So I'm happy for it to be just iOS 11.

**Comment by justJS** [comment]
I also agree it's ok for PDF support to be iOS 11 only, but I really want WeScan to keep iOS 10 support for now. While it's only a small percent, it's still more users.

**Comment by jcampbell05** [comment]
@justJS I'm just meaning to keep PDF iOS11 only and not the framework :) WeScan should support iOS 10 at least for little while longer

**Comment by justJS** [comment]
Yeah, just making sure we're clear :smile:

**Comment by justJS** [comment]
Thoughts on [PSPDFKit](https://pspdfkit.com)? 

Some of it's benefits over Apple's PDFKit: https://pspdfkit.com/guides/ios/current/migration-guides/migrating-from-apple-pdfkit/

**Comment by jcampbell05** [comment]
That costs but I recalled that iOS always had lower level PDF graphics as Quartz was based on PDF.
So we have the CGPDFContextCreate methods (Since iOS 2.0) we can use to easily write a basic PDF with the images into a file.

This should be okay as I think PDFKit was mainly introduced to handle other features beyond the rendering which the Quartz APIs didn't handle (annotations etc).

https://developer.apple.com/documentation/coregraphics/cgpdfcontext

**Comment by justJS** [comment]
👍 What does everyone think about how it should be implemented? I'm thinking, as I said, a host app setting, but any other ideas? Perhaps we could provide both the PDF and typical image back to the host app?

**Comment by Boris-Em** [comment]
Agreed. We could add a new `scannedPDF` property to `ImageScannerResults`. This way users get both a `UIImage` and a PDF back. Let's just make sure first that creating the pdf is very fast.

**Comment by justJS** [comment]
👍 Since there's changes to the ImageScannerResults (the auto rotation) in #41, I can start working on this after that's merged (should be soon).

**Comment by marinofaggiana** [comment]
Hi @justJS I have try your project and is very good, but without save in PDF as document (b/n) is not very palatable ... do you have  start this improvement ?

**Comment by justJS** [comment]
Hi, are you talking about my app, Cards? If so, please send feature requests via Twitter or email, this repo is not for my app. Thanks!

**Comment by marinofaggiana** [comment]
ops sorry, error @

**Comment by justJS** [comment]
Hey, I've done some work on this but am waiting for #80 to be merged (it includes changes to `ImageScannerResults`)

**Comment by justJS** [comment]
I played around with PDF but haven't made a PR yet. I have 3 PRs going right now so I'm just waiting to merge them to clear up my fork 🙂

**Comment by justJS** [comment]
I've started work: #133

**Comment by justJS** [comment]
#133 is done and ready for review 🎉 

(it's a breaking change as it renames variables in `ImageScannerResults`)
