### ISSUE TITLE
Release 1.2.0 on CocoaPods

### ISSUE THREAD

**Issue by y-okady** [WeTransfer/WeScan#204]
Could you please update this library to 1.2.0 on CocoaPods? I'm using this through a library which depends on this. I'd like dark mode support but 1.1.0 doesn't support it. Thanks.

**Comment by sawankumarbundelkhandi** [comment]
Can CocoaPods version be updated to [2.1.0](https://github.com/WeTransfer/WeScan/releases/tag/2.1.0)?

**Comment by AvdLee** [comment]
@sawankumarbundelkhandi we're no longer supporting CocoaPods. I'd recommend migrating to SPM 🙂
