### ISSUE TITLE
adding WeScan manually to Xcode project

### ISSUE THREAD

**Issue by datthanh1911** [WeTransfer/WeScan#206]
I am trying to add a library "WeScan" to my Xcode project manually. I just downloaded the source file from GitHub and by drag and drop, added that we scan folder to my project. Then I tried to import that, but it is giving an error like : "No such module 'WeScan'"
![wD25b](https://user-images.githubusercontent.com/16730701/71928097-b4920c80-314b-11ea-979b-8f2a14f4ae65.png)

**Comment by EricWiener** [comment]
What ended up working for me was dragging the entirety of WeScan-master (I downloaded the zip) into my project directory. Then, I dragged the WeScan.xcodeproj into my project. That ended up working for me.
