### ISSUE TITLE
Edit screen to be optional.

### ISSUE THREAD

**Issue by ahegazi18** [WeTransfer/WeScan#21]
is it possible that will be a mode that you can go from the scan screen to preview screen directly or maybe get the full result in the scan screen and passed to the delegates? 

this way the SDK could fit everyone needs

**Comment by Boris-Em** [comment]
Thtat's a good suggestion, thank you @ahegazi18!
Related to #11.

**Comment by justJS** [comment]
Related to #47

**Comment by jcampbell05** [comment]
Could be handled by the parameter object proposed in #11
