### ISSUE TITLE
setupConstraint Bug on iPhone 8 - 7

### ISSUE THREAD

**Issue by 3rsin3rgul** [WeTransfer/WeScan#215]
Hello I have a bug report on this function;
`    
    private func setupConstraints() {
        let blackFlashViewConstraints = [
            blackFlashView.topAnchor.constraint(equalTo: view.topAnchor),
            blackFlashView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            view.bottomAnchor.constraint(equalTo: blackFlashView.bottomAnchor),
            view.trailingAnchor.constraint(equalTo: blackFlashView.trailingAnchor)
        ]
        
        NSLayoutConstraint.activate(blackFlashViewConstraints)
    }
    `

Is it possible to help me about this.

**Comment by kostapappas** [comment]
@3rsin3rgul 
wrap your ImageScannerController in main thread             
         
         DispatchQueue.main.async {
            self.scannerVC = ImageScannerController()
            self.scannerVC?.imageScannerDelegate = self
            self.scannerVC?.popToRootViewController(animated: false)
            if let vc = self.scannerVC {
                self.present(vc, animated: true)
            }
        }
