### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by Giordano57** [WeTransfer/WeScan#217]
HI,
I downloaded the app but I receive the following error:

/Users/GiordanVico/Library/Developer/Xcode/DerivedData/WeScan-glmyhlhayrkuabfdaiwovacqwddw/Build/Intermediates.noindex/WeScan.build/Debug-iphonesimulator/WeScan.build/Script-503A25EC22FB045E00534850.sh: line 2: ./Submodules/WeTransfer-iOS-CI/SwiftLint/swiftlint.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

Thanks in advance for the help.
Giordano

**Comment by EricWiener** [comment]
I'm getting the same issue.

**Comment by EricWiener** [comment]
I was able to fix this issue by removing SwiftLint from the build phases. Open up the WeScan.xcodeproj and navigate to Build Phases for both the WeScanSampleProject and WeScan framework. Delete the SwiftLint build phase from both.

<img width="1400" alt="Screen Shot 2020-02-29 at 1 08 58 PM" src="https://user-images.githubusercontent.com/18071029/75612802-10966300-5af5-11ea-9d85-82daf6315d14.png">
<img width="1397" alt="Screen Shot 2020-02-29 at 1 09 13 PM" src="https://user-images.githubusercontent.com/18071029/75612804-13915380-5af5-11ea-9ba2-b7007399baeb.png">
