### ISSUE TITLE
how can i scan multiple images at same time

### ISSUE THREAD

**Issue by harishthanniruios** [WeTransfer/WeScan#218]

**Comment by harishthanniruios** [comment]
i want to scan multiple images and i want to make one pdf with all images with pages can anyone help me in this. 

thanks

**Comment by phani697** [comment]
You can do this.

1. First in review screen Add "Next Scan" button and Done button.
2. If user selects "Next Scan" then first save the already scanned image in document directory with some name and push back to scan image. 
3. Now scan another image and save it in document directory with another name.
4. If user selects the done button then make a pdf with images saved in document directory and  remove all saved images.
