### ISSUE TITLE
OpenCV for document edge detection

### ISSUE THREAD

**Issue by jcampbell05** [WeTransfer/WeScan#22]
Thank you for starting this, we were going to open source our own thing at printtapp.com but now we saw you are doing the same we would love to team up with you and build a comprehensive scanning solution. Let me know if you are free for a call or chat.

The current implementation of the rectangle detection is fooled by folded pieces of paper, I would recommend moving to OpenCV edge detection which will do a better job with this

Here is a good article on how Dropbox did it:
https://blogs.dropbox.com/tech/2016/08/fast-and-accurate-document-detection-for-scanning/

**Comment by Boris-Em** [comment]
Hi there @jcampbell05!
Thanks for opening this issue. I'm open to chat! Just shoot me an email (it's on my GitHub profile).

I considered using OpenCV when I started working on **WeScan**. The main reason why I decided not to use it, was the increase in binary size.
Another reason was that our philosophy encourages us to use first party dependencies (Apple) over third party dependencies when possible. Apple seems committed to supporting rectangle detection (it demoed it a few days ago at WWDC 2018), therefore it only makes sense to use this solution.

> The current implementation of the rectangle detection is fooled by folded pieces of paper

Could you tell me more about that?

**Comment by jcampbell05** [comment]
> Hi there @jcampbell05!
> Thanks for opening this issue. I'm open to chat! Just shoot me an email (it's on my GitHub profile).
> 

Cool I'll email you.

> I considered using OpenCV when I started working on WeScan. The main reason why I decided not to use it, was the increase in binary size.
> Another reason was that our philosophy encourages us to use first party dependencies (Apple) over third party dependencies when possible. Apple seems committed to supporting rectangle detection (it demoed it a few days ago at WWDC 2018), therefore it only makes sense to use this solution.
> 

Cool that makes sense, potentially we can look if we can reimplement the OpenCV algorithms using apple technology (for example using Metal)

> The current implementation of the rectangle detection is fooled by folded pieces of paper
> 
> Could you tell me more about that?

So if you have a piece of paper that has been folded up for example in thirds, the current logic will scan one of the thirds.

**Comment by jcampbell05** [comment]
I've discovered https://hochgatterer.me/blog/invoice-scanning/ use the new Vision framework, unfortunately, limits the support of this tool to iOS 11.3 but hopefully may be more reliable and almost 88% of devices are on a version of iOS 11 according to Mixpanel trends.

If this is an issue we can work on implementing the algorithms manually in Metal or using custom Core Image Kernels but I think this is probably the best way forward from using OpenCV or the unreliable Rectangle Core Image algorithm.

I have also discovered that somebody has implemented a 1:1 replica of the Apple scanning UI in the new Notes app. I'm talking to see what scope they have for open sourcing their component, maybe there is some kind of sponsorship we can provide for their development of that piece.
https://hochgatterer.me/blog/invoice-scanning/

**Comment by Boris-Em** [comment]
We could also fall back to the current `CIRectangleFeature` implementation for iOS 10 users.

**Comment by justJS** [comment]
I'm working on an app that uses WeScan, but the rectangle detection is quite shaky. Just wondering, what are the current plans since the last update to this issue? Any ETA on using Vision/getting the Notes scanner open source? Thanks!

**Comment by jcampbell05** [comment]
We're currently busy with other priorities but we are interested in adding vision based scanning by the end of this year. We, unfortunately, couldn't make any progress on the open sourcing.

Our company may be willing to sponsor a developer to take on improving the scanning process (Not sure about WeTransfer's position).

**Comment by justJS** [comment]
I've been hard at work on implementing Vision scanning into WeScan for my app, so since it doesn't seem like you'll be implementing it (soon) i'll try submit a PR if I can get it working (a few bugs left). Stay tuned, i'll give updates.

**Comment by jcampbell05** [comment]
Okay, if there is any way we can be of assistance let us know. We would be happy to provide a test suite of camera images to verify the Vision based scanning :)

**Comment by justJS** [comment]
Sure! It's currently coming along well and I'm implementing some extra features like making it work better on iOS 10 too 👍 

Note: i'll be in SF from tomorrow for 10 days without my laptop, so i'll try get the PR in before then but otherwise it might take a while.

**Comment by jcampbell05** [comment]
Nice one 👍 No worries, maybe place your fork online to make sure any work isn't lost for whatever reason.

Do you just know iOS btw? :)

**Comment by justJS** [comment]
I know quite a lot of frontend web dev (JS, HTML, CSS), but only started learning Swift 3-4 months ago, and no, I don't know Android. Yeah i'll put my fork online soon, but it's kinda broken right now.

**Comment by justJS** [comment]
I've been on vacation for the past month, but I'm now continuing my development. Stay tuned :)

**Comment by justJS** [comment]
I've been on vacation for the past month, but I'm now continuing my development. Stay tuned :)

**Comment by jcampbell05** [comment]
Great work! We're installing on our devices as we speak and will be testing. I'll leave feedback on the PR itself :)

**Comment by justJS** [comment]
👍 (Please note there's a bug where the rotated image isn't actually sent in the completion, but it doesn't happen on the sample project. Fix coming soon)

**Comment by jcampbell05** [comment]
I'm going to close this issue :) as I think @Boris-Em answered the original issue and we've since moved on from Open CV to the vision framework.

I'll carry on any discussion in @justJS 's PR :)
