### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by jcampbell05** [WeTransfer/WeScan#23]
Whilst this is originally an iOS project, we would also like to help port it to Android. Let us know if the best way forward would be for WeTransfer to clone it to Android or perhaps add an android folder.

**Comment by Boris-Em** [comment]
@BartNijland91, and @Alexs784 are our Android developers. I'm not sure exactly what their plan is as far as document scanning goes.

**Comment by Alexs784** [comment]
Hi @jcampbell05,
while we are for sure interested in doing something similar on Android too, we have nothing scheduled anytime soon. Anyway we believe that creating an Android folder into the WeScan repo would be the best option.

**Comment by jcampbell05** [comment]
@Alexs784 Okay good to know :) when we are ready to start doing this, we will create a branch where we prepare project structure :)

**Comment by MincDev** [comment]
Please create a similar project on android!! It is really needed.

**Comment by justJS** [comment]
I'm not an Android developer, but this may be useful if I decide to add an Android version of my app one day. However, i'd like to note that WeScan (iOS) currently uses Apple-only frameworks like CoreImage, Vision, and UIKit, as well as is written completely in Swift, so porting it to Android would be a lot of work (and would result in a different scanner completely).

**Comment by jcampbell05** [comment]
On furhter research we could maybe use MLKit ? https://developers.google.com/ml-kit/ - @Boris-Em could we setup a WeScan Android project to discuss this ?

**Comment by Boris-Em** [comment]
Good idea, @jcampbell05. Here is the repo: https://github.com/WeTransfer/WeScanAndroid

**Comment by Boris-Em** [comment]
Closing this issue as further discussion will now take place on the Android repo.

**Comment by Dhaval11296** [comment]
Hello  where is the Android Code link?

**Comment by Boris-Em** [comment]
Hi @Dhaval11296! 
The repo is here: https://github.com/WeTransfer/WeScanAndroid
But as far as I know, no work has been done yet.

**Comment by Dhaval11296** [comment]
When it will done?,
Any timeline date? For Android.

**Comment by emretekin** [comment]
Any update for Android Repo?  @Boris-Em

**Comment by matthiasnagel** [comment]
@Boris-Em the Android repo is archived. Is there any update about the Android version?

**Comment by jcampbell05** [comment]
If anyone wants it then maybe look into help building it :)

**Comment by fpiraneo** [comment]
> @Boris-Em the Android repo is archived. Is there any update about the Android version?

At the time it seems that the only option is to rely on the "classic and abused" OpenCV version, that produces a very poor results. I don't have the expertise to write down a full kotlin / java version of the scanner nor to port the involved part of OpenCV to native Kotlin / Java. If someone has other options, very glad to know.

**Comment by jcampbell05** [comment]
Other options are:
- RenderScript
- Use something like Hailide which can just be compiled down to different targets like OpenCV, CUDA etc
