### ISSUE TITLE
Carthage Build Failed Xcode 11.4/Swift 5.2

### ISSUE THREAD

**Issue by laferil** [WeTransfer/WeScan#232]
Trying to update the package through Carthage gives a build error. 

`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /HIDDEN/Carthage/Checkouts/WeScan/WeScan.xcodeproj -scheme WeScan -configuration Release -derivedDataPath /Users/HIDDEN/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/WeScan/1.5.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2z/10zjvczj4bj6h71ylv6km36mbw43y7/T/WeScan SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /HIDDEN/Carthage/Checkouts/WeScan)`

**Comment by AkshayNG** [comment]
Having the same issue. Any fix for this ?

**Comment by muiscatron** [comment]
Likewise - same issue.

**Comment by tarasis** [comment]
I'm trying to build nextcloud-ios which uses WeScan. The latest release (1.2.0) has an error linting; basically there is a extra empty line there. 

`Linting 'ShutterButton.swift' (4/33)
/Users/tarasis/Programming/Projects/nextcloud-ios/Carthage/Checkouts/WeScan/WeScan /ImageScannerController.swift:86:1: error: Vertical Whitespace Violation: Limit vertica
l whitespace to a single empty line. Currently 2. (vertical_whitespace)`

This causes the build to fail. (also there is an unknown parameter throwing up a warning `configuration error: 'unused_private_declaration' is not a valid rule identifier` in the lint rules)

**Comment by omsi96** [comment]
same issue here
