### ISSUE TITLE
Magnified corner preview showing rotated image

### ISSUE THREAD

**Issue by wrlf5** [WeTransfer/WeScan#247]
Hello,
thanks for great library !

I found a small issue with magnified corner previews.
Magnified circle preview shows rotated image when initialising ImageScannerController with UIImage. When using image from camera it works great. When for example selecting image from gallery we see correct image in EditScanViewController but image in corner circle is rotated when adjusting the corner. It doesn't happen with every image but its quite common. Tested on iOS 13.5

**Comment by sharjeel-ayubi-cs** [comment]
Any solution for the issue? @wrlf5

**Comment by imrant-toast** [comment]
@wrlf5 @sharjeel-ayubi-cs I am also facing this issue, it occurs during the image which isn't able to detect a rectangle. it polt quad centre of the image. that time corner adjustment not working properly, it's detecting corners at opposite angles of the image. @wetransferplatform. Kindly helps us to fix that issue.

[edited.pdf](https://github.com/WeTransfer/WeScan/files/10776327/edited.pdf)
