### ISSUE TITLE
How to get cropped rectangle image without pushing EditScanViewController?

### ISSUE THREAD

**Issue by UlanNurmatov** [WeTransfer/WeScan#248]
How can I get cropped rectangle image if I don't need EditScanViewController and ReviewViewController?

**Comment by osmansoykan** [comment]
Hi UlanNurmatov,
How did you solve this issue?

**Comment by imrant-toast** [comment]
hi, @UlanNurmatov Kindly help us how to resolve it. it helps us to do as same. @AvdLee
