### ISSUE TITLE
Zoom image bug in EditScanViewController

### ISSUE THREAD

**Issue by NoviceGom** [WeTransfer/WeScan#261]
![IMG_0339](https://user-images.githubusercontent.com/1132357/91006128-8813fd80-e613-11ea-99dc-8ba9481410d3.jpg)
![IMG_0338](https://user-images.githubusercontent.com/1132357/91006137-8e09de80-e613-11ea-907a-49051745cddc.jpg)

Zoomed QuadrilateralView has problem like this.
I thinks exif problem.
Zoomed image rotated 90 degree.
Also bottom left zoomed image looks like not correct.

**Comment by godofgom** [comment]
I found solution at UIImage+Utils.swift.

https://stackoverflow.com/questions/28478293/losing-image-orientation-while-converting-an-image-to-cgimage

I thinks fix to this code. But I'm not sure if this is a clean way.

`
func scaledImage(atPoint point: CGPoint, scaleFactor: CGFloat, targetSize :CGSize) -> UIImage? {

        guard let cgImage = self.cgImage else { return nil }
        
        let fixTargetSize = CGSize(width: targetSize.width / scaleFactor, height: targetSize.height / scaleFactor)
        let fixPoint = CGPoint(x: point.x - fixTargetSize.width/2, y: point.y - fixTargetSize.height/2)
        let rect = CGRect(x: fixPoint.x, y: fixPoint.y, width: fixTargetSize.width, height: fixTargetSize.height)
        
        let rad: (Double) -> CGFloat = { deg in
            return CGFloat(deg / 180.0 * .pi)
        }
        var rectTransform: CGAffineTransform
        switch imageOrientation {
        case .left:
            let rotation = CGAffineTransform(rotationAngle: rad(90))
            rectTransform = rotation.translatedBy(x: 0, y: -size.height)
        case .right:
            let rotation = CGAffineTransform(rotationAngle: rad(-90))
            rectTransform = rotation.translatedBy(x: -size.width, y: 0)
        case .down:
            let rotation = CGAffineTransform(rotationAngle: rad(-180))
            rectTransform = rotation.translatedBy(x: -size.width, y: -size.height)
        default:
            rectTransform = .identity
        }
        
        rectTransform = rectTransform.scaledBy(x: scale, y: scale)
        let transformedRect = rect.applying(rectTransform)
        guard let croppedImage = cgImage.cropping(to: transformedRect) else {
            return nil
        }

        return UIImage(cgImage: croppedImage, scale: scaleFactor, orientation: imageOrientation)
    }
`
