### ISSUE TITLE
Build error with Xcode 12

### ISSUE THREAD

**Issue by duyhct** [WeTransfer/WeScan#269]
Hi WeTransfer, I have build my source with your library and have a issuse like this. Can you support me to solve this? I'm using Xcode 12 and Swift version is 4.2. 

Thank you and waiting for your reply.

![Screen Shot 2020-09-23 at 11 27 33](https://user-images.githubusercontent.com/2231401/93966838-e4437c00-fd8f-11ea-8878-1d12fcd87a47.png)

**Comment by KirillStaroselskiy** [comment]
I have same problem

**Comment by waqasiosdev** [comment]
Hi, is there any way i can detect rectangular shape from an image picked from library ? like on a still image

**Comment by emrcftci** [comment]
> Hi, is there any way i can detect rectangular shape from an image picked from library ? like on a still image

this is not the place where you can find it.
