### ISSUE TITLE
Auto Capture & Enhanced Scanned Image & Batch Scanning

### ISSUE THREAD

**Issue by mital87** [WeTransfer/WeScan#27]
**- Auto Capture:** Detect the document & capture it without pressing camera shutter button.

**- Batch Scanning:** multiple document scan at a time.

**- Enhanced Scanned Image:** Apply image processing to get the clear scanned image like Scannable App, CamScanner App etc...

**- CameraRoll:** Pick the image from camera roll & detect the document.

Please add this feature in your library ASAP.

**Awesome document scanning library.**

**Comment by Boris-Em** [comment]
Thanks for the feedback @mital87! 
I created separate issues for your requested features:
- Auto Capture: #31
- Batch Scanning: #11 
- Camera Roll: #32
