### ISSUE TITLE
Not able to Run 

### ISSUE THREAD

**Issue by devendra-kr-gupta** [WeTransfer/WeScan#273]
Hello WeTransfer Team, 
i am not able to run the source code, as i have downloaded the latest source code from Github. 
i am facing this error - /Users/apple/Library/Developer/Xcode/DerivedData/WeScan-frbjzsxkzcsqocadalmxrqjamoss/Build/Intermediates.noindex/WeScan.build/Debug-iphonesimulator/WeScan.build/Script-503A25EC22FB045E00534850.sh: line 2: ./Submodules/WeTransfer-iOS-CI/SwiftLint/swiftlint.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
Please have a look into the attached screenshot. 

![Screenshot 2020-10-28 at 3 02 57 PM](https://user-images.githubusercontent.com/68465483/97419395-05b7fa80-1930-11eb-94cf-203e2a1f3e0f.png)

Thanks

**Comment by phr85** [comment]
I'm have the same Issue (Xcode 12.2).

**Comment by evandorn** [comment]
You guys can go into the Targets -> Build Phases and delete the phase which is titled "SwiftLint" that fixed it for me. You'll need to do it for both the sample project target and the framework
