### ISSUE TITLE
Zoom Controller Bug When Image Orientation Is Right

### ISSUE THREAD

**Issue by vtamnh14** [WeTransfer/WeScan#287]
Hi there,
I run the example and add an image that has orientation is right.
When I moving the gesture to see the zoom point.
It's a wrong position.

Thanks,

**Comment by dashvlas** [comment]
same here

**Comment by dashvlas** [comment]
@vtamnh14 

I've fixed it by forcing orientation set in init of ZoomGestureController

init(image: UIImage, quadView: QuadrilateralView) {
        self.image = image.forceSameOrientation()
        self.quadView = quadView
    }

Here is the helping func:

`extension UIImage {
    
    func forceSameOrientation() -> UIImage {
        UIGraphicsBeginImageContext(self.size)
        self.draw(in: CGRect(origin: CGPoint.zero, size: self.size))
        guard let image = UIGraphicsGetImageFromCurrentImageContext() else {
            UIGraphicsEndImageContext()
            return self
        }
        UIGraphicsEndImageContext()
        return image
    }
}
`

**Comment by vtamnh14** [comment]
@dashvlas hi Dashvlas,
Thank you for your response.
It's working well.

Regards,
