### ISSUE TITLE
Bug: Preview on iOS 14.3 not displayed

### ISSUE THREAD

**Issue by ErikGro** [WeTransfer/WeScan#291]
The live preview does not get displayed on iOS 14.3.

I implemented the basic example from the README in swift.
When I deploy the app to my iPhone 7 (iOS 14.1) the preview works fine and gets displayed.
But on my other test devices ( iPhone 12 (iOS 14.3 / 18C66) and iPhone X (iOS 14.3 / 18C66) ) the preview does not get displayed, instead only a gray background is presented. This bug is very weird since some days ago the live preview was working on those devices. 

I found out, that this issue is related to the following bug report: https://openradar.appspot.com/FB8785505. 
Apples AV-implementation is somehow broken on iOS 14. 

As sugested in the linked bugreport, I was able to fix this issue with the following line of code in `CaptureSessionManager` :
`
photoOutput.isLivePhotoCaptureEnabled = true
`
I dont know if there is a better way to fix this problem. For now this workaround is working for me.
The bug exists now for multiple months and many users may be affected.
I can't really say on which specific iOS version or on which devices this bug can occur.

Reproduced with:
- iPhone 12 (iOS 14.3 / 18C66)
- iPhone X (iOS 14.3 / 18C66)

**Comment by UlanNurmatov** [comment]
I'm receiving same bug reports from users using iOS 15+, mostly on iPhone X, but also on iPad Air. 
I wonder if this workaround will fix the issue.
