### ISSUE TITLE
Memory Issue on batch scanning

### ISSUE THREAD

**Issue by Talha1275** [WeTransfer/WeScan#297]
Creating an array of controllers for cropping multiple documents at a time causes memory to shoot when delegate method is called and the memory is retained even after the cropped image is received and i have moved to the next screen.

**Comment by Talha1275** [comment]
I have found the eason behind memory retention.
func rotated(by rotationAngle: Measurement<UnitAngle>, options: RotationOptions = []) -> UIImage? {}
The above mentioned method retains the memory when called.
If anyone finds the solution kindly comment.

**Comment by hujaber** [comment]
@Talha1275  did u ever find a solution to this?
