### ISSUE TITLE
Getting only cropped image from captureImage

### ISSUE THREAD

**Issue by osmansoykan** [WeTransfer/WeScan#302]
Hi,
I am using CameraScannerViewController for my custom view. The image in the captureImageSuccess delegate method is the original image. I just want to get a cropped image. How can I do it?
Thanks.

**Comment by osmansoykan** [comment]
There's sure to be a solution, right?

**Comment by Anand-iOS** [comment]
> There's sure to be a solution, right?

//check the results in the delegate method of ImageScannerController
func imageScannerController(_ scanner: ImageScannerController, didFinishScanningWithResults results: ImageScannerResults) {
        // The user successfully scanned an image, which is available in the ImageScannerResults
        // You are responsible for dismissing the ImageScannerController
        
        scanner.dismiss(animated: true)
        self.dismiss(animated: true)
         imageView = results.doesUserPreferEnhancedScan ? results.enhancedScan?.image ?? results.croppedScan.image : results.croppedScan.image)
    }
