### ISSUE TITLE
Batch scanning

### ISSUE THREAD

**Issue by fpiraneo** [WeTransfer/WeScan#306]
Just a question about the batch scanning: Will this feature be implemented on a near term? Or is just a planned feature but with no deadlines? Thanks.

**Comment by fpiraneo** [comment]
Any answer will be strongly apreciated.

**Comment by eltomato89** [comment]
Bump!

**Comment by eltomato89** [comment]
Bump

**Comment by abdullah-lt** [comment]
Bump
