### ISSUE TITLE
Xcode 13.0 beta 3: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by ethanwa** [WeTransfer/WeScan#313]
I know the library is no longer in active development, but I'd hate to see Xcode 13 break it and make it unusable. Anyone have a minute to look at this for a fix?

<img width="1198" alt="Screen Shot 2021-07-17 at 6 52 33 PM" src="https://user-images.githubusercontent.com/1653780/126050997-6a7f1efe-46d7-4ae4-8a7f-0f531b3d7392.png">

The change in Xcode 13 beta 3 release notes:

_Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)_

https://twitter.com/twannl/status/1415643870512226307: 

<img width="593" alt="Screen Shot 2021-07-17 at 6 57 26 PM" src="https://user-images.githubusercontent.com/1653780/126051068-29d6def9-9011-4c21-a319-682c70852589.png">

**Comment by BasThomas** [comment]
I'll take a look.

**Comment by BasThomas** [comment]
Hey @ethanwa, when are you observing this issue? Do you have steps to reproduce? Building both the `WeScan` as well as the `WeScanSampleProject` schemes using beta 5 work fine for me.
