### ISSUE TITLE
CameraRoll Support (Gallery)

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#32]
Make it possible to select a picture from the Camera Roll.

**Comment by justJS** [comment]
This would require quite a lot of changes based on how the code is currently written.

**Comment by jcampbell05** [comment]
Maybe a 2.0 feature? I think a good idea but should be deferred until we have a good workflow with the camera. I think we get one method of scanning done well then we can focus on adding a second later.

**Comment by justJS** [comment]
I feel like if we do this the host app should present option and pass it into WeScan. Because, for example, the host app might never want users to pick from photo library.

**Comment by Boris-Em** [comment]
Yes, I agree with @justJS. WeScan shouldn't get into the business of presenting the gallery. It should simply scan an image that's provided directly to it. 
This is probably not too much work.

**Comment by justJS** [comment]
Ah that wasn’t exactly what I meant but yeah, that would work too 👍

So we’d have the preferences object with a passed in image OR scan from camera

**Comment by Boris-Em** [comment]
I think that we should probably create a new, convenience `init` in `ImageScannerController` which would take a image and delegate as parameters.
```swift
    convenience init(image: UIImage, delegate: ImageScannerControllerDelegate) {
        self.init()
        self.imageScannerDelegate = delegate
        // TODO: scan image
    }
```

**Comment by justJS** [comment]
Yeah, however, couldn’t this be implemented in the existing proposal for preferences? Reduces the need for more initialized, this can just be handled in the main one.

**Comment by justJS** [comment]
Sorry, deleted my comment because I completely misread your comment about *not* making this part of preferences.

I guess that works too 😆

**Comment by jcampbell05** [comment]
Perhaps we just have a object the host app can pass an image to and does the rect detection algo the scanning VC does to the frame buffers (Perhaps the VC uses it too).

The host app can then pass this result to the edit VC if they want user to edit it or get a image from it.

**Comment by justJS** [comment]
Done! #110

**Comment by justJS** [comment]
(In case anyone's wondering, I'm basically just making the initializer for `ImageScannerController` skip the `ScannerViewController` completely and jump to `EditScanViewController` if a custom image is passed in)

**Comment by piotrros** [comment]
How do you do that? I've ran an example project from github, but it won't compile:

```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) {
        picker.dismiss(animated: true)
        
        guard let image = info[.originalImage] as? UIImage else { return }
        let scannerViewController = ImageScannerController(image: image, delegate: self)
        present(scannerViewController, animated: true)
    }
```

but I cannot find such a constructor for ImageScannerController class. How can I use ImageScannerController and provide initial UIImage so it immediately goes for edge detection?

**Comment by piotrros** [comment]
I've found the issues: I was using wrong version, instead of:

`pod 'WeScan', '>= 0.9'`

you have to use:

`pod 'WeScan', :git => 'https://github.com/WeTransfer/WeScan.git'`

then, there are missing methods and classes I was missing.

**Comment by jcampbell05** [comment]
@fatenumber25 please don't double post :)
