### ISSUE TITLE
barTintColor not working in iOS 15

### ISSUE THREAD

**Issue by Bgihe** [WeTransfer/WeScan#320]
barTintColor not working in iOS 15
https://developer.apple.com/forums/thread/682420

iOS15:
![](https://imgur.com/MSt3NuC.jpg)

iOS14:
![](https://imgur.com/ajMmR1J.jpg)

ImageScannerController.swift
now:
`public required init() {
    let scannerViewController = ScannerViewController()
    super.init(rootViewController: scannerViewController)
    navigationBar.tintColor = .black
    navigationBar.isTranslucent = false
    self.view.addSubview(blackFlashView)
    setupConstraints()
}
`

fix barTintColor not working in iOS 15 :

`
public required init() {
    let scannerViewController = ScannerViewController()
    super.init(rootViewController: scannerViewController)
    navigationBar.tintColor = .black
    navigationBar.isTranslucent = false

    if #available(iOS 13.0, *) {
        let navBarAppearance = UINavigationBarAppearance()
        navBarAppearance.titleTextAttributes = [NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 20), .foregroundColor: UIColor.white]
        navBarAppearance.backgroundColor = UIColor.white
        scannerViewController.navigationController?.navigationBar.standardAppearance = navBarAppearance
        scannerViewController.navigationController?.navigationBar.scrollEdgeAppearance = navBarAppearance
    }

    self.view.addSubview(blackFlashView)
    
    setupConstraints()
}
`

**Comment by anagstef** [comment]
Any updates on this?

**Comment by AparParmar** [comment]
Here is the solution.
1.]. In ImageScannerController class put the following code:
func navigationBarSetup(barColor: UIColor) {
        if #available(iOS 13.0, *) {
            let standardAppearance = UINavigationBarAppearance()
            standardAppearance.backgroundColor = barColor
            self.navigationBar.standardAppearance = standardAppearance
            self.navigationBar.scrollEdgeAppearance = standardAppearance
        }
    }


2.].  Inside ScannerViewController class put the following code in viewWillAppear override method.
if let imageScannerController = navigationController as? ImageScannerController {
       imageScannerController.navigationBarSetup(barColor: .black)
 }
 
 
3.]    Inside the ScannerViewController class find the following method:
func captureSessionManager(_ captureSessionManager: CaptureSessionManager, didCapturePicture picture: UIImage, withQuad quad: Quadrilateral?) { }

this method has already some code as follows:

       activityIndicator.stopAnimating()
        let editVC = EditScanViewController(image: picture, quad: quad)
        navigationController?.pushViewController(editVC, animated: false)
        
        shutterButton.isUserInteractionEnabled = true



just put following code in the method and you are done:

 if let scannerNavigationController = navigationController as? ImageScannerController {
            scannerNavigationController.navigationBarSetup(barColor: .white)
        }


So final code of method in step 3 will be as follows:

func captureSessionManager(_ captureSessionManager: CaptureSessionManager, didCapturePicture picture: UIImage, withQuad quad: Quadrilateral?) {
        activityIndicator.stopAnimating()
        
        let editVC = EditScanViewController(image: picture, quad: quad)
        if let scannerNavigationController = navigationController as? ImageScannerController {
            scannerNavigationController.navigationBarSetup(barColor: .white)
        }
        navigationController?.pushViewController(editVC, animated: false)
        
        shutterButton.isUserInteractionEnabled = true
    }



Note: You will need to unlock particular class pod file to edit them. Run the app and it should work.
