### ISSUE TITLE
Fix iOS15 navBar background color

### ISSUE THREAD

**Issue by alikenski** [WeTransfer/WeScan#325]
Do you have any plans for fixing this issue?

**Comment by ronitvasoya** [comment]
Work for me

let scannerViewController = ImageScannerController()
scannerViewController.imageScannerDelegate = self
scannerViewController.modalPresentationStyle = .fullScreen
scannerViewController.navigationBar.backgroundColor = .white // Change Background Color of navigation bar
scannerViewController.useImage(image: img)
present(scannerViewController, animated: true)

**Comment by AparParmar** [comment]
Check my this answer: https://github.com/WeTransfer/WeScan/issues/320#issuecomment-990900521
