### ISSUE TITLE
Review screen transparency issue 

### ISSUE THREAD

**Issue by cansavrun** [WeTransfer/WeScan#328]
<img width="318" alt="Ekran Resmi 2022-01-16 22 25 33" src="https://user-images.githubusercontent.com/49312193/149674780-c30f1ea2-c1bf-4602-9e63-c6f23b78bf11.png">
How can I solve this issue?

**Comment by SonuChopra** [comment]
Add the line below when opening the scanner
        let scannerViewController = ImageScannerController()
        scannerViewController.view.backgroundColor = .black <----
        scannerViewController.imageScannerDelegate = self
        self.viewController!.present(scannerViewController, animated: true)

**Comment by cansavrun** [comment]
@SonuChopra  Thank you. It worked for me.

**Comment by apouche** [comment]
the `view.backgroundColor` was not enough for our project, there were still black `tintColor` for the `ReviewController` navigation items. I ended up doing something like this:

```
extension ImageScannerController {
  func ios15Fix(backgroundColor: UIColor = .black, backgroundImage: UIImage? = nil) {
    if #available(iOS 15, *) {
      let barAppearance = UINavigationBarAppearance()
      barAppearance.configureWithOpaqueBackground()
      barAppearance.backgroundColor = backgroundColor
      barAppearance.backgroundImage = backgroundImage
      barAppearance.shadowImage = UIImage(color: .black)
      navigationBar.isTranslucent = false
      navigationBar.standardAppearance = barAppearance
      navigationBar.scrollEdgeAppearance = barAppearance
      navigationBar.tintColor = .white
      navigationBar.shadowImage = UIImage()
      view.backgroundColor = .black
    }
  }
}
```
