### ISSUE TITLE
Corner Detection Error

### ISSUE THREAD

**Issue by imrant-toast** [WeTransfer/WeScan#345]
@AvdLee  #247  I am also facing this issue, it occurs during the image which isn't able to detect a rectangle. It plots the quad centre of the image. that time corner adjustment not working properly, it's detecting corners at opposite angles of the image. Kindly helps us to fix that issue.

[edited.pdf](https://github.com/WeTransfer/WeScan/files/10776876/edited.pdf)

**Comment by AvdLee** [comment]
@imrant-toast we're currently not actively maintaining this repo, other than reviewing Pull Requests and creating new releases. Feel free to contribute with a PR and we make sure to review accordingly!
