### ISSUE TITLE
Change Background Color

### ISSUE THREAD

**Issue by imrant-toast** [WeTransfer/WeScan#346]
I would like to change the background colour for ImageScannerController, it comes in black colour. Kindly helps to fix it. @AvdLee 
![Simulator Screen Shot - iPhone 13 Pro Max - 2023-02-19 at 18 06 18](https://user-images.githubusercontent.com/89177897/219948394-06ef4d33-abba-440f-a59d-ae0bc6216d47.png)

**Comment by AvdLee** [comment]
@imrant-toast we're currently not actively maintaining this repo, other than reviewing Pull Requests and creating new releases. Feel free to contribute with a PR and we make sure to review accordingly!
