### ISSUE TITLE
Carthage Dependency "WeScan" has no shared framework schemes

### ISSUE THREAD

**Issue by NSnik** [WeTransfer/WeScan#353]
Dependency "WeScan" has no shared framework schemes
version  "2.1.0"

**Comment by mstapfner** [comment]
I'm also facing the same issue: 
`Dependency "WeScan" has no shared framework schemes`

**Comment by BasThomas** [comment]
Oh noes, sorry to hear that. We're no longer actively supporting Carthage — please use Swift Package Manager instead.
