### ISSUE TITLE
Cocoa Pod Issue 

### ISSUE THREAD

**Issue by faisyleo** [WeTransfer/WeScan#36]
When Install "we Scan" through Cocoapod then following error will become : 
[!] CocoaPods could not find compatible versions for pod "WeScan":
  In Podfile:
    WeScan (~> 1.0.0)

None of your spec sources contain a spec satisfying the dependency: `WeScan (~> 1.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by Boris-Em** [comment]
**WeScan** is currently in v0.9. Can you try updating your Podfile with `WeScan (>=0.9)` please?
If that fixes the problem, we need to update the README.

**Comment by faisyleo** [comment]
I try this but Problem is still exist. What we do know @Boris-Em ?

**Comment by Boris-Em** [comment]
Thanks for reporting back @faisyleo!
