### ISSUE TITLE
pod trunk version seems stuck at 1.7 / updating WeScan in a Flutter dependency

### ISSUE THREAD

**Issue by espbee** [WeTransfer/WeScan#368]
Wondering if anyone has advice about getting WeScan to update as a trunk pod in a Flutter project. It seems stuck at 1.7. I've tried updating cocoapods and tried updating the project and project/example/ios podspecs, but nothing seems to change. This is a dependency I'm using in my own project, but I'm not the dependency author; I've filed an issue there, but am trying to work it out on my own in the meantime.

If I run pod trunk info WeScan, the versions stop at 1.7.

in example/ios/Manifest.lock I find

'
SPEC REPOS:
  trunk:
    - WeScan
'

and then below in that same file there is

'
SPEC CHECKSUMS:
  WeScan: fed582f6c38014d529afb5aa9ffd1bad38fc72b7
'

Could anyone point me in a better direction?

**Comment by BasThomas** [comment]
Hi @espbee, we unfortunately do not support CocoaPods for our repositories anymore. You can use it as a manual addition to your project or use Swift Package Manager.
