### ISSUE TITLE
Crash on xcode 15.0 

### ISSUE THREAD

**Issue by dairy96** [WeTransfer/WeScan#373]
I've added that library to my project but when I run it I'm receiving this error:

Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:196:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:199:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:202:5

Swift Compiler Error (Xcode): Stored properties cannot be marked unavailable with '@available'
/Users/abdulmalekdery/tessafold/mobile/ios/Pods/WeScan/WeScan/ImageScannerController.swift:205:5

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

**Comment by BasThomas** [comment]
Hey @dairy96, can you share more about which version of the library you are using? Are you using Swift Package Manager? What's your Package.swift looking like?

**Comment by fsljivo** [comment]
I have the same issue. I'm using Cocoapods and I have updated the library version to the latest one, but the issue still persists.
