### ISSUE TITLE
"Stored properties cannot be marked unavailable with '@available'"

### ISSUE THREAD

**Issue by Tak783** [WeTransfer/WeScan#376]
When I fetched the package, I got the following issue
`Stored properties cannot be marked unavailable with '@available'

<img width="933" alt="Screenshot 2023-12-12 at 13 01 39" src="https://github.com/WeTransfer/WeScan/assets/3129728/a667c140-c8a1-4c5f-8f0f-96045a4fc57e">

Please can you fix this, thank you :)

**Comment by BasThomas** [comment]
Which version of the package are you using? This should be resolved using 3.0.0.

**Comment by OrbitalMan** [comment]
Well, the [WeScan CocoaPods](https://cocoapods.org/pods/WeScan) page says that the last supported version is 1.7.0 (I guess this is according to the provided podspec or something...) Could you please check or advise on how to get that 3.0.0 version using CocoaPods?

**Comment by BasThomas** [comment]
We unfortunately don't support CocoaPods anymore. You can include it using Swift Package Manager or manually.
