### ISSUE TITLE
Add Flash Support

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#38]
Having the option to use the flash of the device would be a great improvement when in low light.

**Comment by jcampbell05** [comment]
Maybe as part of this we bring UI closer to that of the one Apple uses in Notes ?

**Comment by justJS** [comment]
This and the new UI is in #41.

**Comment by justJS** [comment]
Fixed in #41

**Comment by Boris-Em** [comment]
Closed as fixed with #41.
