### ISSUE TITLE
Apple Privacy Manifest with Required Reasons

### ISSUE THREAD

**Issue by observableobject** [WeTransfer/WeScan#382]
Apple is requiring all SDKs to include a Privacy Manifest as part of their bundled SDK.  It would be great if WeScan could include this.  It's not too complicated to make. 

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by ethanwa** [comment]
I hope someone out there can get this in ASAP!

**Comment by peagasilva** [comment]
Hi all!

Just a heads up that we're working on it internally and will have an update soon.

For all who are wondering if a privacy manifest will be required for all 3rd party libraries, that's the case only for the commonly used libraries, and `WeScan` is not part of the [list](https://www.msclb.store/support/third-party-SDK-requirements/).

![CleanShot 2024-04-15 at 11 08 49@2x](https://github.com/WeTransfer/Diagnostics/assets/5387088/a4dd30b6-ed50-44b8-b560-b86b3c818d06)

So if you add the privacy manifest to you app, you should be good - unless you use a 3rd party library that is commonly used and it doesn't have a privacy manifest.

Cheers!
