### ISSUE TITLE
A little suggestion.

### ISSUE THREAD

**Issue by JunkyTang** [WeTransfer/WeScan#384]
Since this library is written in Swift, would it be more appropriate to change NSObjectProtocol to AnyObject here in the 
public protocol ImageScannerControllerDelegate: NSObjectProtocol?

This way, my class public class App {} can conform to your protocol.

**Comment by BasThomas** [comment]
Thanks for bringing this up, @JunkyTang! That sounds reasonable; I'd encourage you to open a pull request for this change!
