### ISSUE TITLE
Rotation Support on Edit Screen

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#39]
Having the option to rotate the image on the Edit screen, would solve a few edge cases where the orientation of the image isn't correct.

**Comment by justJS** [comment]
Thoughts on rotating it to "up" (portrait) based on how the picture was taken? Basically, using the accelerometer to rotate the image automatically.

**Comment by justJS** [comment]
This was already filed as #5, maybe one of the issues should be closed?

**Comment by jcampbell05** [comment]
Is there an example of when this would be useful to the user ?

**Comment by justJS** [comment]
Now that #41 is in I am heavily in favor of implementing this. While auto rotate works very well in many cases a few people/users have been frustrated when it doesn't work for them.

**Comment by justJS** [comment]
Any thoughts/comments on location for the rotation buttons before I try and make a PR? 

I'm not sure if they'd fit better on the "edit" screen (but this would be annoying as we'd have to rotate the quad and image together) or "review" screen (which isn't really meant for this).

**Comment by Boris-Em** [comment]
This is something that @sagalundqvist and @StijnEversdijk can look at when they find some time.

**Comment by justJS** [comment]
I think we've basically settled on it being Scan -> Crop -> "Edit" instead of "Review" #80

**Comment by justJS** [comment]
Can someone make an icon for this? I'm working on this but I can't find a good (free) icon.

(Just send an SVG and I can create the correct sizes)

**Comment by justJS** [comment]
Something similar to this would work. When I get around to making a PR, do we want 2 buttons (left/right) or only one @Boris-Em?


![](https://storage.googleapis.com/igeeksblog/wp-content/uploads/Rotate-Photos-in-iPhone.jpg)

**Comment by Boris-Em** [comment]
I think that 1 should be enough. @StijnEversdijk, @sagalundqvist, thoughts?

**Comment by StijnEversdijk** [comment]
One icon should be fine, I'll make an icon either today or tomorrow!

**Comment by justJS** [comment]
🙂 Thanks!

**Comment by StijnEversdijk** [comment]
![image](https://user-images.githubusercontent.com/5574228/49656285-3db4ac80-fa3d-11e8-9036-8ecd36ca5d44.png)

@justJS Sorry for the delay! Do you think the icon above would work? What direction do we rotate the image in, so I'll adjust the arrow the right way. Do you want it delivered as a PDF?

**Comment by justJS** [comment]
Yeah, that looks great! Perhaps a little less rounded to fit in with out enhance icon 👍 

Could you send it as an SVG? If not PDF is fine 🙂

(I’m not sure on direction yet, but I’m pretty sure it’ll be as that icon shows, so we have consistency with the Photos app)

**Comment by StijnEversdijk** [comment]
@justJS Good call, changed it to a 1px line width: 
```
<svg width="21" height="25" xmlns="http://www.w3.org/2000/svg"><g stroke="#000" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round"><path d="M13.5 23.914h-12a1 1 0 0 1-1-1v-12a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1zM12.621 6.157l-2.828-2.83L12.621.5"/><path d="M9.793 3.328h4.414a6 6 0 0 1 6 6v1"/></g></svg>```

**Comment by justJS** [comment]
Thanks! Working on the rotate PR 🙂
