### ISSUE TITLE
Q: I am unable to refer WeScan Project 

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [WeTransfer/WeScan#40]
Hi,
I am trying to download project manually and make some changes.

Manually
Just download the project, and drag and drop the "WeScan" folder in your project.

I downloaded and added to my project
Steps:
1.Add fiels to "MyProjectnamehere"
2. Selected dowloaded WeScan folder
With Options: a. copy items if needed(unchecked)
                        b. create groups(selected)
3 Now i would like to add WeScan.framework but could not find it in downloaded folder.
4. I open complete sample project. There i see framework. So I picked that frame work and added to 
    my project.
5. When use **_import WeScan_**, it says no such module. 

Could anyone help. I am very new to swift and Xcode.

**Comment by Boris-Em** [comment]
Maybe this would help you? https://github.com/ITHHKN/WeScan/blob/c9a2c9f1dd3aba5d001330eab993ccba478c7d56/README.md

**Comment by avinashramireddy-rapidd** [comment]
**_Just download the project, and drag and drop the "WeScan" folder in your project._**

This **"WeScan" _folder_** misleading as there is folder with WeScan and I just dropped that folder. It should have been WeScan.xcodeproj

That solved my issue after going through screenshots attached in readme.md

**Comment by EricWiener** [comment]
What ended up working for me was dragging the entirety of WeScan-master (I downloaded the zip) into my project directory. Then, I dragged the WeScan.xcodeproj into my project. It was important to drag the WeScan-master folder in otherwise GitHub wouldn't keep track of it and when cloning the repository it wouldn't be able to find WeScan.
