### ISSUE TITLE
Make Scanning View Available

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#47]
By making the scanning UIView public, we would give users the opportunity to implement their own flow if they don't want to use the one provided by WeScan.

**Comment by justJS** [comment]
Wouldn't there be no point in using WeScan then? I'm sorry if I misunderstood what you meant.

**Comment by Boris-Em** [comment]
They'd still get all of the rectangle detection from the camera. They would just be able to customize what they want to do after having detected a rectangle.

**Comment by justJS** [comment]
As, so the post scanning UI? As in they could use the scanned rect + image without the rest of WeScan's editing UI?

**Comment by Boris-Em** [comment]
Exactly @justJS!

**Comment by justJS** [comment]
👍 I think this would make sense as part of an enhancement for more host app provided settings as I commented recently.

**Comment by jcampbell05** [comment]
@Boris-Em we are going to be adding this project into our app. so I will be happy to guide you with this if and when we need this :)

**Comment by godofmadness** [comment]
So, is there some customization added ( from what was discussed )? Is there a way to create own flow?
