### ISSUE TITLE
Implement Rotation Buttons on Edit Screen

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#5]
Right now, users can't rotate the picture after it has been taken. Users should have the possibility to rotate the picture on the Edit Screen.

**Comment by justJS** [comment]
This was already filed as #39, maybe one of the issues should be closed?

**Comment by jcampbell05** [comment]
I think this is the better of the two issues.

**Comment by justJS** [comment]
I feel this should be closed in favor of #39 which already has some discussion in it.

**Comment by Boris-Em** [comment]
Closed as duplicate of #39.
