### ISSUE TITLE
Add a contribution doc

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeScan#50]
We should add a contribution doc, for which we can reuse the one from UINotifications.

**Comment by jcampbell05** [comment]
Is this the same as https://github.com/WeTransfer/WeScan/blob/develop/CODE_OF_CONDUCT.md ?

**Comment by Boris-Em** [comment]
I think that this is what @AvdLee is talking about: 
https://github.com/WeTransfer/UINotifications/blob/master/CONTRIBUTING.md

**Comment by jcampbell05** [comment]
Cool I'm happy to do another PR for this :)

**Comment by justJS** [comment]
Hey @avdlee I know this issue is closed now but I just realized that maybe we should have a Contribuing section on the Readme too? What do you think? (I can make a PR if it’s a good idea)

**Comment by AvdLee** [comment]
That would absolutely be great! Go ahead and I'll review it together with @Boris-Em 💪
