### ISSUE TITLE
Localiztion / internationalization

### ISSUE THREAD

**Issue by millertfin** [WeTransfer/WeScan#51]
HI,

Is there a way to alter or override the texts displayed by the ImageScannerController, according to the device language?

Regards
Tobias

**Comment by AvdLee** [comment]
@Boris-Em can you elaborate on this?

**Comment by justJS** [comment]
@millertfin The issue of localizations not working is in #67, but nothing will be translated unless the localizations have already been contributed to WeScan. 

Can we close this @boris-em?

**Comment by Boris-Em** [comment]
Like @justJS said, let's keep track of our localization issues on #67.
