### ISSUE TITLE
Rethink the zooming corner 

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeScan#61]
> @nickseidel thanks for thinking with us here. I had the same discussion with @Boris-Em before, but he mentioned that we copied the exact same behaviour as the notes iOS app. Although we should handle Apple as a serious example, we might want to revisit this ourselves for better UX.

## What can we improve?
We might want to show the zoomed circle in an offset of the touch point, so it's visible in all scenarios. This does mean we step away from the Apple way of doing this, but the question is either way whether users are used to this Apple behaviour and whether we should just do the best for our users instead.

**Comment by CavalcanteLeo** [comment]
I’d preffer apple way

**Comment by Boris-Em** [comment]
@CavalcanteLeo - Apple's way is currently implemented. Just like in Notes, right now, you can drag anywhere on the screen, and it will grab the closest corner. You don't have to tap on the corner.
The proposition is to move away from Apple's way.

**Comment by CavalcanteLeo** [comment]
Misunderstood, I thought i were talking about the zoom position that is under my finger.

That's the way i prefer:
![whatsapp image 2018-09-24 at 15 37 53](https://user-images.githubusercontent.com/1735944/45971710-1c344f00-c010-11e8-8ccd-11e4f8f373bb.jpeg)
![whatsapp image 2018-09-24 at 15 37 52](https://user-images.githubusercontent.com/1735944/45971711-1c344f00-c010-11e8-9f9c-4e46bb916d6e.jpeg)


that's not under my finger, it's a little more to the top of the object, then m finger doesn't hide it

**Comment by Boris-Em** [comment]
@CavalcanteLeo - This is not the feature in Notes we're talking about. Give the document scanning feature in Notes a try, and you'll see that the behavior is exactly the same.
And as I said, you shouldn't drag on the corner, but next to it :)

**Comment by AvdLee** [comment]
I still wonder whether that note scanning behaviour is what users expect. It's not natural to tap next to the point you want to move, is it?

Are we able to A/B test or research this?

**Comment by nickseidel** [comment]
Or how about just making it optional?
For example:

let scannerVC = ImageScannerController()
scannerVC.allowOutsideCornerTap = false
scannerVC.cornerZoomOffsetEnabled = true

**Comment by justJS** [comment]
How about some helper text at the bottom like Notes has?
![image-1-1](https://user-images.githubusercontent.com/19729335/46278495-de4ba380-c598-11e8-9f39-09387f28ac10.jpg)

**Comment by saormart** [comment]
I think that @AvdLee  is talking about something like this (picture) right ?
![img_0019](https://user-images.githubusercontent.com/8941296/47306774-571fa780-d5fb-11e8-99cd-1c60006d5a57.jpg)

**Comment by AvdLee** [comment]
@saormart you're totally right here. It's not about explaining like @justJS is suggesting. I think it's clear for users that they _can_ drag the corners around. The issue is that once you start dragging, it's possible that the user starts dragging by touching the corner directly, which makes it impossible with the current implementation to see the zoomed circle as it's underneath the finger.

@saormart's example would make this possible.

I'm fine with making this an opt-in feature, but I would challenge to make the offset the default instead.

**Comment by justJS** [comment]
I think the we can probably guess quite easily whether the user is tapping on or near the corner, and choose based on that?

I think that would be a great solution for everyone.
