### ISSUE TITLE
Objective-c

### ISSUE THREAD

**Issue by CavalcanteLeo** [WeTransfer/WeScan#63]
Is it compatible with objective-c?

**Comment by Albarahakami** [comment]
I am also having issues integrating it with objective-c. It seems like it needs to be updated to Swift 4.2 in order for it to work properly.

Used pods + manual installation and both generated different issues.

**Comment by Boris-Em** [comment]
Thanks for the feedback @Albarahakami. 
Feel free to contribute to the project to add Objective-C support!

**Comment by tathag** [comment]
can any one tell how to integrate this library with objective c project ?

**Comment by takhil** [comment]
I am also faced issue integrating with both objective-c and swift. I don't why it happens.
issue : 
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can anyone me to resolve this?

**Comment by jcampbell05** [comment]
The project has now been updated to 4.2,  so hopefully will work once the podspec is updated

**Comment by CoderMaurice** [comment]
Anyone tell me if it can work in Objective-C?

**Comment by jcampbell05** [comment]
No body has tried since the update, I guess. Should be easy to import from swift though I would imagine.

**Comment by CavalcanteLeo** [comment]
I will try by the end of this weekend

**Comment by takhil** [comment]
> Anyone tell me if it can work in Objective-C?

Hi Integrated Swift Frame work in Objective-c project. It works for me. What you have do is

1.  First set Your Deployment target to 10.0+
2. Create a dummy swift class in your project. Now xCode asks you bridgingHeader. Create Bridging 
     header. In bridging header file you need add objective-c class (#import"myClass.h") where you 
     want to WeScan class.
3. Now in your class (#import"myClass.m") add  "#import <yourProjecName.swift.h>". 
4. Now drag and drop add WeScan folder from sample project.
5. In in your class (#import"myClass.h") add "@class ImageScannerController;"
6. Now in  your button action write below code. It will Work.
"
 ImageScannerController *obj = [[ImageScannerController alloc]init];
 [self presentViewController:obj animated:YES completion:nil];
"

**Comment by takhil** [comment]
> I am also having issues integrating it with objective-c. It seems like it needs to be updated to Swift 4.2 in order for it to work properly.
> 
> Used pods + manual installation and both generated different issue

I wrote the comment how to use WeScan in Objective-c.

**Comment by CavalcanteLeo** [comment]
which version? `0.9.2` ???

**Comment by CavalcanteLeo** [comment]
the version 0.9.2 is not available via cocoapods, then u can use 
`pod 'WeScan', :git => 'https://github.com/WeTransfer/WeScan/'` 

it's now working properly again

**Comment by takhil** [comment]
> Objective

Swift delegate methods not worked in objective - c. So you need get image data through Notifications only. Need to add notification in scanViewController and call that notification in finish button action in Review Controller. 

1. User may get errors like "Multiple name files.." like this. Then they need to change info.plist name in weScan folder. 

2. Now in your class (#import"myClass.m") add "#import <yourProjecName_swift.h>". This must be need to in .m file only.

I am adding a sample project to this comment. To how notifications called do global search with "Notification". [
[WeScanManually.zip](https://github.com/WeTransfer/WeScan/files/2610164/WeScanManually.zip)
](url)

**Comment by kattaliraees** [comment]
import Foundation

class DocumentScanner : UIViewController {
    
    @objc public var imageScannerAction: (NSDictionary) -> () = {(results : NSDictionary) -> () in}
    @objc public var scannerViewController : ImageScannerController = ImageScannerController()
    @objc public var scannerPresentingViewController : UIViewController = UIViewController()
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    @objc public func presentScanner() {
        self.scannerViewController = ImageScannerController()
        self.scannerViewController.imageScannerDelegate = self
        self.scannerPresentingViewController.present(self.scannerViewController, animated: true)
    }
    
    
}

extension QLDocumentScanner :  ImageScannerControllerDelegate {
    func imageScannerController(_ scanner: ImageScannerController, didFinishScanningWithResults results: ImageScannerResults) {
        self.imageScannerAction(["scannedImage": results.scannedImage, "originalImage" : results.originalImage, "enhancedImage" : results.enhancedImage as Any, "doesUserPreferEnhancedImage" : (results.doesUserPreferEnhancedImage)]);
        scanner.dismiss(animated: true) {
            
        }
    }
    
    func imageScannerControllerDidCancel(_ scanner: ImageScannerController) {
        self.imageScannerAction(NSDictionary())
        scanner.dismiss(animated: true) {
            
        }
    }
    
    func imageScannerController(_ scanner: ImageScannerController, didFailWithError error: Error) {
        self.imageScannerAction(NSDictionary())
        scanner.dismiss(animated: true) {
            
        }
    }
}

UI Action Obj C
@property(nonatomic, strong) DocumentScanner *documentScanner;
-(void)presentScannerVC {
    self.documentScanner = [[QLDocumentScanner alloc] init];
    self.documentScanner.imageScannerAction = ^(NSDictionary *results) {
        NSLog(@"%@", results);
    };
    
    self.documentScanner.scannerPresentingViewController = self;
    
    [self.documentScanner presentScanner];
}

**Comment by Saad-twinbit** [comment]
@takhil u r the boss... Thank u very much bro.

**Comment by AnandPGautam** [comment]
@takhil Thank you for attaching the sample app. I tried to do the same what you have mentioned and integrated in your sample. but I am getting below error : 

<img width="604" alt="screenshot 2019-02-01 at 7 37 04 pm" src="https://user-images.githubusercontent.com/40850195/52127662-be1c1600-2658-11e9-8cbd-d21d0299f8d0.png">

Please advise.

**Comment by takhil** [comment]
> @takhil Thank you for attaching the sample app. I tried to do the same what you have mentioned and integrated the same in my App. but I am getting below error :
> 
> <img alt="screenshot 2019-02-01 at 7 37 04 pm" width="604" src="https://user-images.githubusercontent.com/40850195/52127662-be1c1600-2658-11e9-8cbd-d21d0299f8d0.png">
> 
> Please advise.
 "
    ImageScannerController *obj = [[ImageScannerController alloc]init];
    [self presentViewController:obj animated:YES completion:nil];
    "
Use the above initial method. Then also you may get some errors in swift classes. Then you nee import "import UIKit" where you got errors.

**Comment by justJS** [comment]
Does the sample app work for you? I know that it is repetitive but this seems to be fixed for others - can you check that you have the header and are using ‘import WeScan’ at the top of the file?

**Comment by justJS** [comment]
If not it’s best that you create a new issue so we can track your issue better, this issue is already closed.

**Comment by takhil** [comment]
> If not it’s best that you create a new issue so we can track your issue better, this issue is already closed.

Sample app works for me. When I created new app and tried to do same things I got issues. It may be compiler issues. I resolved all issues and again its working for me.

**Comment by thlonglytll** [comment]
Hi all, Could anyone help me?
