### ISSUE TITLE
Localizations aren't working when WeScan is used as a pod

### ISSUE THREAD

**Issue by justJS** [WeTransfer/WeScan#67]
I'm trying to make a PR to add Portuguese and Italian localizations to WeScan, but I'm not able to get WeScan working with localizations when it's a pod in another project, as pods are compiled without bundles, so the localizations aren't being found by NSLocalizedString.

I think there's 2 options we could use to solve this issue:
- Ask the host app to provide localizations (I don't think this is very elegant, but if we do this we have to remove the custom bundle from NSLocalizedString because it's making it impossible at the moment)
- Find a way to deliver localizations together with WeScan

On the second issue, I've investigated (in https://github.com/justJS/WeScan/tree/private) but haven't been able to figure it out. I'd appreciate if anyone with experience with this can help out?

**Comment by florentmorin** [comment]
In PR #64 , I was able to make it working by changing `WeScan.podspec`.

Especially in this commit 58a1b720e9486fe784b114b13a4a303e300593ac :
- replacing `spec.source_files` by a specific version
- adding localizations in `spec.resources`

**Comment by justJS** [comment]
Can someone else help to verify that this is indeed fixed in #64? If so, i'd be in favor of closing this issue and merging #64.

**Comment by justJS** [comment]
This has been fixed.
