### ISSUE TITLE
Cannot install as a POD

### ISSUE THREAD

**Issue by yangricardo** [WeTransfer/WeScan#69]
Even with de pod install, there are a error on `import WeScan`

**Comment by saormart** [comment]
Did you check your local "Pods" folder ?
Did you try build it before use the "import WeScan" ?

**Comment by yangricardo** [comment]
yes, the WeScan pod has a lot of errors on build process in new projects with Swift 4.2, even on drag and drog de WeScan folder into my project... only using it by editing the sample project in this repository....

**Comment by basememara** [comment]
Experiencing same issues with Swift 4.2.

**Comment by basememara** [comment]
Figured out you have to use Xcode 10's legacy build system under `File > Workspace/Project Settings...` and works fine. So this is an issue with Xcode 10+ and sounds like there's a radar on it: https://github.com/CocoaPods/CocoaPods/issues/8073

**Comment by yangricardo** [comment]
Thanks for the help! 
But i think the pod version still needs to be updated, i have to parse some lines of code to run the same version of this repository.

**Comment by jcampbell05** [comment]
We have a PR to update the podspec which may be causing the issue #65

**Comment by jcampbell05** [comment]
I guess we should cut a new release @Boris-Em  and then we can close this

**Comment by Boris-Em** [comment]
I'll work on a new version today.

**Comment by yangricardo** [comment]
That's nice to know this project is going to be improved! It helped me a lot combining in a my OCR solution :)

**Comment by AvdLee** [comment]
Way later than planned, but the new release is out. Closing this issue as fixed, let me know if any issues occur.
