### ISSUE TITLE
Just a comment for future enhancement!

### ISSUE THREAD

**Issue by saormart** [WeTransfer/WeScan#70]
First of all, great framework!
I just would like to suggest some things that could be great for your nice frame-work and kick ass other similar!
So would be great to add:

topCenter
bottomCenter
leftCenter
rightCenter
(Like the image)
With this, the user could adjust the manual crop quickly if he wants to move the lines top down left right!

Another nice feature would be add option to filter the cropped image as black and white (Use GPUImage to enhance scanned documents) or something similar !

![img_0271](https://user-images.githubusercontent.com/8941296/47304517-e1b0d880-d5f4-11e8-9fbe-02107d1236c1.PNG)

**Comment by Boris-Em** [comment]
Thanks for your nice words @saormart! Could you open 2 different issues for each enhancement you propose?
