### ISSUE TITLE
Enhancement to adjust the manual crop

### ISSUE THREAD

**Issue by saormart** [WeTransfer/WeScan#71]
As per request [based on this topic](https://github.com/WeTransfer/WeScan/issues/70#event-1919905172)

So would be great to add:

topCenter
bottomCenter
leftCenter
rightCenter
(Like the image)
With this, the user could adjust the manual crop quickly if he wants to move the lines top down left right!

![img_0271](https://user-images.githubusercontent.com/8941296/47363862-d7024c00-d6a5-11e8-8bba-0c2c40b447e2.PNG)

**Comment by justJS** [comment]
Hey, could you make it clearer what this would do? I don't understand why center points would help as we're scanning documents/rectangles?

**Comment by saormart** [comment]
Consider done !
Thanks !

**Comment by saormart** [comment]
The center point could help user to adjust both corners let's say at the same time!
Let's say you want to move both corners (top right and bottom right) and the same time to make some adjustment, and would be great if while the user is moving it to adjust, it kind try to predict the paper / document border and kind of "adjust" to the borders or something like that!

**Comment by justJS** [comment]
Sounds like a great idea to snap to edges! I’m not sure how easy that would be, however. What about just snap to edges on all corners rather than center points?

**Comment by justJS** [comment]
I’m aware of CamScanner  😃 
As for the user experience, my implementation was completely seamless - you just tap a bar button and it applies the GPUImage adaptive thresholding.
