### ISSUE TITLE
Filter the cropped image as black and white or even better based on user selection!

### ISSUE THREAD

**Issue by saormart** [WeTransfer/WeScan#72]
As per request [based on this topic](https://github.com/WeTransfer/WeScan/issues/70#event-1919905172)

Would be a nice feature to add option to filter the cropped image as black and white (Use GPUImage to enhance scanned documents) or something similar !
What I really mean, would be nice to have different options for the user to adjust images manually like the  brightness, contrast let's say "Details" (like a fine adjustment)
Note: Based on user selection, let's says that user want to scan a receipt, so we could have some "pre-setting" to process it and give the user a better user experience!

**Comment by justJS** [comment]
I think this is a great idea! However, a few things:

1. I feel having tons of options and sliders would over complicate what is currently a nice, focused scanner
2. This is (kinda) a duplicate of #49, especially if we only enhance the image rather than add custom adjustment

**Comment by saormart** [comment]
At this point I agree with you ! The scanner is awesome! Maybe all this features could be another framework, or may just another separated class to do this kind of job!
I'm trying to figure out a way to do it just like the [#49](https://github.com/WeTransfer/WeScan/issues/49)
But anyway, if anybody could contribute with it, and it could be added to the example code would be handy!

**Comment by justJS** [comment]
I had an example working with GPUImage, I’m waiting for #41 which is almost merged then I’ll send in a PR 😃

**Comment by saormart** [comment]
That's a great news ! Let me know when this happen, and I want to test it for sure ! :)

**Comment by saormart** [comment]
By the way, I figure out how to do it with opencv2, but if with GPUImage could get better results, I'll move to it ! I'll close this topic due [#49](https://github.com/WeTransfer/WeScan/issues/49)
