### ISSUE TITLE
Implement Camera Rotation when User rotates Device (iPad)

### ISSUE THREAD

**Issue by LambdaDigamma** [WeTransfer/WeScan#76]
When using the WeScan Framework on an iPad, the Camera View is not being rotated when the User rotates the Device. (eg. from Portrait to Landscape Mode)

**Comment by justJS** [comment]
Yes, I believe that’s how it’s meant to be.

**Comment by pavanvalluru** [comment]
Is this planned to fix or already done ?

**Comment by jbarros35** [comment]
its not working at all

**Comment by dulgan** [comment]
Still an issue today, will try to fix it with a PR

**Comment by willm132** [comment]
Has anyone found a fix to allow this in landscape only, not portrait?
