### ISSUE TITLE
Swift 4.2 support for iOS 12 SDK

### ISSUE THREAD

**Issue by jcampbell05** [WeTransfer/WeScan#77]
Some of the methods in UIKit have been renamed again (Please apple can this be the last time!)

We just need to refactor some of the methods to use the correct form of methods such as `bringSubviewToFront`.

**Comment by jcampbell05** [comment]
Seems like it's my mistake. Our project may be in a Swift 3 compatibility mode and Xcode doesn't explain the change is referring to Swift 2 -> 3 migration

**Comment by justJS** [comment]
🤔 I'm not sure if this is still an issue, but #41 and the PR before it should have updated the method names already.

**Comment by jcampbell05** [comment]
I'm investigating something in my Xcode is very confused :) I'll track this down, I suspect it's an issue on my side and not this project.
