### ISSUE TITLE
Support 2x Camera

### ISSUE THREAD

**Issue by Boris-Em** [WeTransfer/WeScan#8]

**Comment by jcampbell05** [comment]
@Boris-Em could you add more details ?

**Comment by Boris-Em** [comment]
I think that this is referring to the dual cameras that some iOS devices have (Plus models and X).

**Comment by justJS** [comment]
I honestly don’t see the point of this as right now I have to move (kinda) far with 1x already 🤔

**Comment by Boris-Em** [comment]
Makes sense, let's close this issue. We can always revisit it in the future.
