### ISSUE TITLE
Old Screen Cleaning

### ISSUE THREAD

**Issue by mehyaz** [WeTransfer/WeScan#86]
Hello, I'm running the application with a button. I'm taking the picture and there's no problem. When I finish my work, click the button to run the application again, the old screen image is coming. Every time I press the button, I want a new screen to be opened. I want the old image erased. How can I do that.

**Comment by justJS** [comment]
Hey, you need to make sure you're creating a new `ImageScannerController()` every time, so you don't accidentally present the old one (which still has the old image). Let me know if you have any troubles after doing this 🙂

**Comment by justJS** [comment]
Upon further thought, I think we should implement a method to reset the `ImageScannerController` to it's original state (I'm thinking of a use case where the controller is displayed in an always-available pull up state from the bottom of the screen). Thoughts?

**Comment by justJS** [comment]
If this is agreed on I can make a quick PR (shouldn't be too hard) to add a reset method when I have some time 🙂

**Comment by Boris-Em** [comment]
Sounds like a plan! Thanks again for your contributions!

**Comment by jviloriam** [comment]
Good day! I end up with the same problem to reset the controller to get various images, so i added this code but i do not think it's the best solution. 

In the "ImageScannerController" set this new function
`public func reset(){
        let scanner = ScannerViewController()
        self.setViewControllers([scanner], animated: false)
        navigationBar.tintColor = .black
        navigationBar.isTranslucent = false
        self.view.addSubview(blackFlashView)
        setupConstraints()
    }`

**Comment by EricWiener** [comment]
I'd be happy to create a PR for this if there is still interest in this. Please let me know and I'll go ahead and work on it @julianschiavo
