### ISSUE TITLE
Use Github project boards

### ISSUE THREAD

**Issue by justJS** [WeTransfer/WeScan#88]
We should enable Projects on the repo so we can have a todo, in progress, and done Kanban (trello) style board.

This way we can easily track duplicate/new issues and implementations, and note when we are working on an issue.

**Comment by Boris-Em** [comment]
Good idea, this is done now.

**Comment by justJS** [comment]
Hey, I noticed Projects were enabled but there’s no projects yet. If you make some projects/let others edit projects we can add the existing issues in for a quicker look at what still needs to be done, is being worked on, etc.
