### ISSUE TITLE
iPhone X layout issues

### ISSUE THREAD

**Issue by askeland** [WeTransfer/WeScan#92]
Looks like the changes in #83 did not work fully as expected. On iPhone X the flash icon is vertically aligned center and the Auto/manual button is vertically aligned in the bottom. Not sure which one of them that is most corrrect, but... Added a screenshot:

![img_ead76fef4674-1](https://user-images.githubusercontent.com/867061/49158417-61cc0b80-f322-11e8-950a-7e3169099da1.jpeg)

**Comment by jcampbell05** [comment]
May need to account for safe area

**Comment by askeland** [comment]
They account for the safe area, but I believe that the UIToolbar is not optimal for this. You see a lot of users with same issue on SO and UIToolvar does not like custom heights. It might be better to just use an UIView as “toolbar” and UIButtons instead.

**Comment by jcampbell05** [comment]
@askeland yes I think thats the best solution since I'm not sure if we really need a UIToolbar

**Comment by justJS** [comment]
Well, someone can open a PR for that but it’s gonna be *really* annoying as you can’t use UIBarButtonItems or the auto blurred appearance :/

**Comment by askeland** [comment]
@justJS What was the main motivation for going away from just keeping it in a UINavigationBar?

**Comment by justJS** [comment]
🤔 I don’t think we ever considered it, before the toolbar it *was* the default nav bar but flash/auto scan didn’t exist. Wouldn’t It not have the same style tho? I’ll check it out later when I’m on my computer.

**Comment by jcampbell05** [comment]
Blurred there are UIVisualEffectViews :) so you don't need a UIToolbar for that

**Comment by justJS** [comment]
I know, but you probably can't add one to a nav bar? Haven't checked yet

**Comment by justJS** [comment]
I did as suggested in #94 (manually creating blur view to make it look more like Camera app). Thanks for the suggestions @jcampbell05 @askeland. 🙂

**Comment by justJS** [comment]
Here's a screenshot 😛
![simulator screen shot - iphone xs - 2018-11-30 at 19 02 21](https://user-images.githubusercontent.com/19729335/49285483-79e28d00-f4d2-11e8-9e53-6d6cc28a9986.png)

**Comment by AvdLee** [comment]
@justJS is this one fixed? If so, you can close it :)

**Comment by justJS** [comment]
Fixed in#94
