### ISSUE TITLE
Crop the image selected from gallery

### ISSUE THREAD

**Issue by iosdroid** [WeTransfer/WeScan#95]
its possible to crop the image selected from gallery

**Comment by justJS** [comment]
Hey @iosdroid, I've made a new PR with the changes you requested: #110 

Feel free to head over and leave a comment if you have any changes you'd prefer, and follow that PR to get notified when this is added to the WeScan framework 🙂

**Comment by rajnishios** [comment]
when I load the photo from the gallery it's doesn't crop automatically....
