### ISSUE TITLE
entry point (_main) undefined. for architecture arm64 

### ISSUE THREAD

**Issue by Saad-twinbit** [WeTransfer/WeScan#98]
"entry point (_main) undefined. for architecture arm64" When I added this folder to Objective c project.

**Comment by justJS** [comment]
Hey, have you read through the [Obj-C instructions](
https://github.com/WeTransfer/WeScan/#objective-c)? If so, could you double check to make sure you followed the steps correctly? Thanks!

**Comment by Saad-twinbit** [comment]
![screenshot 2019-01-03 at 2 41 55 pm](https://user-images.githubusercontent.com/46312725/50629206-d3245d00-0f65-11e9-968a-d78828b4fa5e.png)

After following [Obj-C instruction](https://github.com/WeTransfer/WeScan/#objective-c) I can run my project, but when try to present WeScan this error occured.

**Comment by justJS** [comment]
Hey, I'm not too familiar with Objective-C but it seems you may have made a mistake when importing WeScan. 

Could you try to follow the steps on this answer? https://stackoverflow.com/questions/8815200/receiver-type-for-instance-message-is-a-forward-declaration

It may also be that you've forgotten to `#import` WeScan.

**Comment by justJS** [comment]
Hey @Saad-twinbit, have you managed to resolve this?

**Comment by justJS** [comment]
This is fixed by updating the Objective C instructions in #143 /cc @avdlee
